### ISSUE TITLE
OAuth2 access token response parsing fails with nested JSON object with Keycloak 16.1.0

### ISSUE THREAD

**Issue by laurocesar** [spring-projects/spring-security#10666]
**Describe the bug**
The same as #6463

I have the same issue #6463 in version 5.4.5 and Keycloak 16.1.0:

```java
Caused by: java.lang.RuntimeException: com.nimbusds.oauth2.sdk.ParseException: Unexpected type of JSON object member with key mtls_endpoint_aliases
        at org.springframework.security.oauth2.client.registration.ClientRegistrations.parse(ClientRegistrations.java:232)
        at org.springframework.security.oauth2.client.registration.ClientRegistrations.lambda$oidc$0(ClientRegistrations.java:157)
        at org.springframework.security.oauth2.client.registration.ClientRegistrations.getBuilder(ClientRegistrations.java:209)
        ... 113 common frames omitted
Caused by: com.nimbusds.oauth2.sdk.ParseException: Unexpected type of JSON object member with key mtls_endpoint_aliases
        at com.nimbusds.oauth2.sdk.util.JSONObjectUtils.getGeneric(JSONObjectUtils.java:161)
        at com.nimbusds.oauth2.sdk.util.JSONObjectUtils.getJSONObject(JSONObjectUtils.java:827)
        at com.nimbusds.oauth2.sdk.as.AuthorizationServerMetadata.parse(AuthorizationServerMetadata.java:2042)
        at com.nimbusds.openid.connect.sdk.op.OIDCProviderMetadata.parse(OIDCProviderMetadata.java:1362)
        at org.springframework.security.oauth2.client.registration.ClientRegistrations.parse(ClientRegistrations.java:229)
        ... 115 common frames omitted
Caused by: com.nimbusds.oauth2.sdk.ParseException: Unexpected type: class java.util.LinkedHashMap
        at com.nimbusds.oauth2.sdk.util.JSONUtils.to(JSONUtils.java:100)
        at com.nimbusds.oauth2.sdk.util.JSONObjectUtils.getGeneric(JSONObjectUtils.java:159)
        ... 119 common frames omitted
```

**Comment by jgrandja** [comment]
@laurocesar This exception is thrown in the Nimbus class [OIDCProviderMetadata](https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/src/fbd7845dab2c248febde2ad415221723e7a98c0c/src/main/java/com/nimbusds/openid/connect/sdk/op/OIDCProviderMetadata.java#lines-1587). See this [comment](https://github.com/spring-projects/spring-security/issues/6463#issuecomment-951649845) for further info.

Note, you would get the same error if you used `OIDCProviderMetadata.parse()` directly.

Please report this issue with [Nimbus](https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/src/master/).
