### ISSUE TITLE
DefaultLdapAuthoritiesPopulator throws NullPointerException

### ISSUE THREAD

**Issue by Andreas-PPI** [spring-projects/spring-security#12090]
**Describe the bug**
I want to evaluate the LDAP entries of a user to derive the role of the user. The attribute I have chosen is 'description' of the groups the user is a member of. The corresponding configuration in the security.xml is as follows:
```
<ldap-authentication-provider server-ref=...
  group-search-filter="(member={0})" group-role-attribute="description" role-prefix="none"
  user-context-mapper-ref="instantUserContextMapper" />
```

If 'description' is not assigned for one of the entries, a NullPointerException occurs in the class DefaultLdapAuthoritiesPopulator.
I think this happens in line 172:
`String role = record.get(this.groupRoleAttribute).get(0);`
In this case `record.get(this.groupRoleAttribute)` returns null.

I'm using spring-security-ldap:5.7.3 - the newest version which works with Java 8.
Previously I used V3.1.1, no NullPointerException was thrown there. Instead such entries were skipped, which I think is the better behavior.

**To Reproduce**
Add a group without description to your LDAP-groups or remove description from existing group.

**Expected behavior**
Unspecified attribute values should be treated as empty strings.
Alternatively, the affected entries can be omitted so that DefaultLdapAuthoritiesPopulator.getGrantedAuthorities() 
returns fewer entries than are present in the LDAP.

**Stack trace**
```
java.lang.NullPointerException
  at org.springframework.security.ldap.userdetails.DefaultLdapAuthoritiesPopulator.lambda$new$0(DefaultLdapAuthoritiesPopulator.java:172)
  at org.springframework.security.ldap.userdetails.DefaultLdapAuthoritiesPopulator.getGroupMembershipRoles(DefaultLdapAuthoritiesPopulator.java:228)
  at org.springframework.security.ldap.userdetails.DefaultLdapAuthoritiesPopulator.getGrantedAuthorities(DefaultLdapAuthoritiesPopulator.java:202)
  at org.springframework.security.ldap.authentication.LdapAuthenticationProvider.loadUserAuthorities(LdapAuthenticationProvider.java:197)
  at org.springframework.security.ldap.authentication.AbstractLdapAuthenticationProvider.authenticate(AbstractLdapAuthenticationProvider.java:81)
  at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182)
  at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:201)
  at org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:85)
  at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
  at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
  at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
  at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
  at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
  at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)
  at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)
  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)
  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)
  at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
  at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
  at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  at java.lang.Thread.run(Thread.java:748)
```

**Comment by sjohnr** [comment]
Thanks for reporting this, @Andreas-PPI!

It looks as though the change in 63607ee213c74d84ef52167ac08a2f67eb0b2f89 changed the way attribute values are searched/returned and subsequently mapped, resulting in the possible NPE. Would you be interested in submitting a PR to fix the issue?

I believe the `authorityMapper` would need to be changed to return `null` in this case, and the for-loop below would skip `null` return values.

https://github.com/spring-projects/spring-security/blob/f9a2d22b405905e635351ea78579831d7b321869/ldap/src/main/java/org/springframework/security/ldap/userdetails/DefaultLdapAuthoritiesPopulator.java#L227-L229

**Comment by dkodippily** [comment]
@sjohnr can I work on this :) ?

**Comment by Andreas-PPI** [comment]
Hi @sjohnr , hi @dkodippily ,
I checked out the source code but didn't change anything. I wanted to start with it this morning, but if you'd like, you can take it over.

**Comment by dkodippily** [comment]
Thanks @Andreas-PPI , have you done anything on this yet, if not I'll pick this.

**Comment by Andreas-PPI** [comment]
Hi @dkodippily , no I've done nothing until now. I'm looking forward for your changes.

**Comment by dkodippily** [comment]
@Andreas-PPI @sjohnr , managed to run some code and reproduce the issue, but I'm facing some issues building the latest master, Execution failed for task ':checkstyleNohttp', companing about documents with http, trying to get my build right at the moment.

**Comment by dkodippily** [comment]
> Thanks for reporting this, @Andreas-PPI!
> 
> It looks as though the change in [63607ee](https://github.com/spring-projects/spring-security/commit/63607ee213c74d84ef52167ac08a2f67eb0b2f89) changed the way attribute values are searched/returned and subsequently mapped, resulting in the possible NPE. Would you be interested in submitting a PR to fix the issue?
> 
> I believe the `authorityMapper` would need to be changed to return `null` in this case, and the for-loop below would skip `null` return values.
> 
> https://github.com/spring-projects/spring-security/blob/f9a2d22b405905e635351ea78579831d7b321869/ldap/src/main/java/org/springframework/security/ldap/userdetails/DefaultLdapAuthoritiesPopulator.java#L227-L229

Returning null from the authorityMapper is still results in a NPE, how about filtering it from the method calling point as below
`for (Map<String, List<String>> role : userRoles) {
			if(role.keySet().contains(this.groupRoleAttribute)) {
				authorities.add(this.authorityMapper.apply(role));
			}
		}`

**Comment by Andreas-PPI** [comment]
Hi @dkodippily ,
I think this will work. It would also have the advantage that the solution would work for other similar implementations of authorityMapper.

**Comment by dkodippily** [comment]
Hi @sjohnr  I Agree. , @Andreas-PPI 

Allowing null returns from the authorityMapper is a much safer way of doing it, for the two scenarios the group-role-attribute is defined without a value assignment or completely omitted i can check and return null from the authorityMapper as below.
<img width="1520" alt="Screen Shot 2022-11-16 at 10 53 17 PM" src="https://user-images.githubusercontent.com/19679713/202149481-794bfcda-6a10-4371-931b-42fb1fbb5564.png">

However through the calling method `Set<GrantedAuthority> getGroupMembershipRoles` the returning Set will allow a single null value, and I can remove it as shown below.
<img width="1680" alt="Screen Shot 2022-11-16 at 11 07 10 PM" src="https://user-images.githubusercontent.com/19679713/202152056-453daa69-9c92-4b80-89e3-26eb65e388c7.png">

**Comment by Andreas-PPI** [comment]
Hi @sjohnr , I agree with your points. Whether that meant a breaking change, I wasn't sure. But I can understand your argument.

Hi @dkodippily , I agree with your first change, so that `authorityMapper` returns `null` for the two scenarios "undefined or empty group-role-attribute".
I would omit the second change. This way the caller can decide for himself what to do with a `GrantedAuthority = null`. In case of doubt it can be removed there itself.

**Comment by Andreas-PPI** [comment]
Or is there a problem I do not see with the `null` entry?

**Comment by Andreas-PPI** [comment]
Hi @sjohnr ,

> I believe this would be a breaking change as well, is that right?

Compared to throwing an NPE, both behaviors are breaking changes. ;-)
I thought it is better to have a `GrantedAuthority` entry for each entry in the LDAP as well. I had overlooked that these are in a `Set`, same roles are mapped just like `null` only as 1 entry, so that the number can or will deviate anyway. In this case it is probably better not to supply the entry `null`, because probably nothing useful can be done with it anyway.

**Comment by dkodippily** [comment]
Hi @sjohnr  Thanks for the feedback , @Andreas-PPI , yes a null would not make any sense, also it will again throw a NPE when mapping the authority list to a Set through `AuthorityUtils.authorityListToSet` , this method only asserts if the input list is null or not , not the elements. So as as @sjohnr suggested better not to allow null at all.

**Comment by Andreas-PPI** [comment]
Hi @dkodippily , I hava a question to your code sample. `authorityMapper` can return `null`, see code sample from @sjohnr . In this case `authority` is `null`. Then `Assert.notNull()` will throw an `IlegalArgumentException`. This is not the desired behavior. Do you agree?

Why throws `AuthorityUtils.authorityListToSet()` a NPE? This method return a `HashSet`, which implementation allows `null` entries - more exactly: one `null` entry.

Regardless, we agreed that `getGroupMembershipRoles()` should not contain `null` entries in its returned `Set`.

**Comment by sjohnr** [comment]
Hi @dkodippily. Sorry if I was unclear. When I said

> I think it would be better not to allow a null to be added at all.

I meant add a null check and do not add the `null` to the collection. At this point, I think I'd prefer if you submitted a PR and we can review the code more easily there. What do you think?

**Comment by dkodippily** [comment]
Hi @Andreas-PPI , yes we don't need to call ``` Assert.notNull() ```, this is how I tested the code, simply can check for null before calling ``` authorities.add(authority); ``` inside ```getGroupMembershipRoles()```.

True, since we agreed  ```getGroupMembershipRoles()``` should not contain null there will be no NPEs, but I was answering your previous question, If we were to let that single null to go through ```AuthorityUtils.authorityListToSet()``` will break with a NPE due to below call, it is extracting the String role value from each ```GrantedAuthority```.  I'll raise a PR, lets keep improving.
```
for (GrantedAuthority authority : userAuthorities) {
			set.add(authority.getAuthority());
		}
```

**Comment by sjohnr** [comment]
Also @dkodippily:

> is it better to add a separate ldif file with "undefined or empty group-role-attribute" and load it in a new test class rather adding new entries to the test-server.ldif ?

Yes, feel free to add a new ldif file for this case. I think that would be the preference unless an existing test needs to be changed for some reason. I have not reviewed it to determine whether it does or not.

**Comment by dkodippily** [comment]
> Hi @dkodippily. Sorry if I was unclear. When I said
> 
> > I think it would be better not to allow a null to be added at all.
> 
> I meant add a null check and do not add the `null` to the collection (e.g. skip the element). At this point, I think I'd prefer if you submitted a PR and we can review the code more easily there. What do you think?

Hi @sjohnr , Yes its high time now :)

**Comment by dkodippily** [comment]
Hi @sjohnr , @Andreas-PPI PR is raised #12258

**Comment by sjohnr** [comment]
@dkodippily thanks for the PR! I will look into it at the first opportunity. Just a heads up, I'm currently working hard on content for the SpringOne virtual conference to be recorded soon, so reviews and responses may be delayed.
