### ISSUE TITLE
Authentication not propagated correctly after migrating to SB3

### ISSUE THREAD

**Issue by hqrd** [spring-projects/spring-security#12877]
Hello,

I'm trying to migrate from Spring boot 2 to 3 and having an issue I can't seem to solve, despite having tried multiple solutions.

**My problem:**
I use `@EnableMethodSecurity` to use the `@PreAuthorize` annotation. But when calling any endpoint which is **secured with `@PreAuthorize`**, I get a 401 with the error `AuthenticationCredentialsNotFoundException`. This used to work in Spring boot 2.

**My code:**
My filterChain looks like that:

```java
@Bean
public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
	http.cors()
			.and().csrf().disable()
			.sessionManagement((sessions) -> sessions
					.sessionCreationPolicy(SessionCreationPolicy.STATELESS)
			)
			.authorizeHttpRequests(auth -> {
                         ...
								.requestMatchers("/myendpoint/**").fullyAuthenticated()
                         ...
			})
			.oauth2ResourceServer(oauth2 -> oauth2
					.jwt(jwt -> jwt
							.decoder(createDecoder())
							.jwtAuthenticationConverter(this::convert)
					)
			);

	return http.build();
}
```

The `convert()` method is correctly invoked and returns an `AbstractAuthenticationToken`. But for some reason, in the `ObservationAuthorizationManager`, the `Authentication` is not found (it passes once at the same line, with the Authentication correctly set, the second one then returns AuthenticationCredentialsNotFoundException`)

![image](https://user-images.githubusercontent.com/22975382/225903219-8320ba76-e666-4331-bfa3-0f94382751d7.png)

Any help appreciated if this isn't an issue from spring-security 😄

**Comment by hqrd** [comment]
Issue is still occuring with 3.0.5. Tried `@EnableMethodSecurity` and `@EnableGlobalMethodSecurity(prePostEnabled = true)`
My configuration is
```
@Configuration
@EnableGlobalMethodSecurity(prePostEnabled = true)
// or @EnableMethodSecurity
```
And the error :
```
org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:350)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:214)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:218)
	at jdk.proxy2/jdk.proxy2.$Proxy308.findById(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:281)
	at org.springframework.data.repository.support.ReflectionRepositoryInvoker.invoke(ReflectionRepositoryInvoker.java:220)
	at org.springframework.data.repository.support.ReflectionRepositoryInvoker.invokeFindById(ReflectionRepositoryInvoker.java:121)
	at org.springframework.data.repository.support.CrudRepositoryInvoker.invokeFindById(CrudRepositoryInvoker.java:80)
	at org.springframework.data.rest.core.support.UnwrappingRepositoryInvokerFactory$UnwrappingRepositoryInvoker.invokeFindById(UnwrappingRepositoryInvokerFactory.java:91)
	at org.springframework.data.rest.webmvc.RepositoryEntityController.getItemResource(RepositoryEntityController.java:507)
	at org.springframework.data.rest.webmvc.RepositoryEntityController.getItemResource(RepositoryEntityController.java:320)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:537)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at org.springframework.test.web.servlet.TestDispatcherServlet.service(TestDispatcherServlet.java:72)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:631)
	at org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFilter(MockFilterChain.java:165)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:132)
	at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
	at org.springframework.security.web.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:399)
	at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:297)

```

**Comment by NRaf** [comment]
@hqrd were you able to resolve this? Having this same issue.

**Comment by hqrd** [comment]
> @hqrd were you able to resolve this? Having this same issue.

No, I tried many things but always facing another error, or I have to re-implement too many things to make it work. So I paused my SB3 migration for now.

**Comment by NRaf** [comment]
In case anyone else has the same issue, removing the following line fixed the problem for me.

`SecurityContextHolder.setStrategyName(SecurityContextHolder.MODE_INHERITABLETHREADLOCAL);`

I'm still using `@EnableGlobalMethodSecurity(prePostEnabled = true)`.

If I use `@EnableMethodSecurity`, the application fails to connect to MongoDB and doesn't start up. 🤷‍♂️

**Comment by rameshkrishnanme** [comment]
i'm also in the same boat, doing SB3 migration. 

yes this fixes the issue (removing)-`SecurityContextHolder.setStrategyName(SecurityContextHolder.MODE_INHERITABLETHREADLOCAL);`

without removing, if I restart the app once after the first start, then also works without issues.

**Comment by FrenchFriesFiesta** [comment]
This appeared in our case as well, and is blocking us from upgrading to SB3. We have a Quartz job base class which sets a system type authentication before running:
```java
    @Override
    public void execute(JobExecutionContext context) throws JobExecutionException {
        try {
            Authentication authentication = SecurityUtils.getSystemUserAuthentication();
            SecurityContextHolder.getContext().setAuthentication(authentication);
            executeJob(context);
        } finally {
            SecurityContextHolder.clearContext();
        }
    }

    public abstract void executeJob(JobExecutionContext context);

```

All of our jobs inherit this, but since upgrading to spring security `6.1.0` and spring-boot `3.1`, our annotated methods are throwing the same exception (`An Authentication object was not found in the SecurityContext`):
```java
@PreAuthorize("hasAuthority('ROLE_SYSTEM')")
@Transactional(readOnly = true)
public List<Foo> thisIsCalledByAJob() {
}

```

Removing `SecurityContextHolder.setStrategyName(SecurityContextHolder.MODE_INHERITABLETHREADLOCAL);` fixes the issue, but it looks like a workaround to me. Any updates on this issue?

**Comment by MarkusWb** [comment]
This seems to be the same issue as discussed in https://github.com/spring-projects/spring-security/issues/13866
The solution proposed in this issue fixed the problem for me.

**Comment by ThomasAFink** [comment]
Same issue commenting out `//SecurityContextHolder.setStrategyName(SecurityContextHolder.MODE_INHERITABLETHREADLOCAL);`did it for me.

```
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.web.client.RestTemplateAutoConfiguration;
import org.springframework.boot.web.client.RestTemplateBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.context.annotation.Profile;
import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.http.SessionCreationPolicy;
//import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.web.SecurityFilterChain;

@Configuration
@Profile("!no-security")
@EnableWebSecurity
@EnableMethodSecurity(securedEnabled = true, prePostEnabled = true)
@Import(RestTemplateAutoConfiguration.class)
public class SecurityConfiguration {

    @Autowired
    private RestTemplateBuilder restTemplateBuilder;

    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        http
                // Add the custom filter before the CsrfFilter
                .csrf().disable()
                .cors().and() // Apply CORS configuration from application.yaml
                .authorizeHttpRequests((requests) -> requests.requestMatchers("/**",
                        "/actuator/info",
                        "/actuator/health",
                        "/actuator/health/liveness",
                        "/actuator/health/readiness",
                        "/actuator/metrics").permitAll()
                        .anyRequest().authenticated())
                .sessionManagement()
                .sessionCreationPolicy(SessionCreationPolicy.IF_REQUIRED);

        //SecurityContextHolder.setStrategyName(SecurityContextHolder.MODE_INHERITABLETHREADLOCAL);
        return http.build();
    }

    @Bean
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }
}
```
