### ISSUE TITLE
Concurrent session management not working. Setting Constraint on maximum session for session management

### ISSUE THREAD

**Issue by emmanuelU17** [spring-projects/spring-security#12931]
**Bug description**
The bug is related to session management in the SecurityFilter chain. Setting max session in session management is ignored.

**To Reproduce**
No test cases written yet but I when a user signs in using multiple browsers, constraint set for max session is ignored  

**Expected behavior**
The SecurityFilter chain should be able to manage sessions for each user and enforce the maximum constraint set for the number of sessions per user. If a user attempts to create a new session (login) after reaching the maximum constraint,  older or oldest session should be invalid.

**Sample**
[https://github.com/emmanuelU17/restful-session-authentication](url)

![image](https://user-images.githubusercontent.com/80619808/227926228-c6c6e7c4-23d0-4378-8fb7-8f5e1e9df438.png)

**Comment by emmanuelU17** [comment]
2. Also I noticed a second issue which is related to using JPA to create the session table and attribute table. An error is thrown while trying to remove expired sessions using the cleanup-cron. My question now is it wrong to rely on JPA to build up a table based on an Entity class even though the entity class'(s) is following the model or schema recommended by spring security?
     
       `Caused by: java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`session_db`.`spring_session_attributes`, CONSTRAINT `SPRING_SESSION_ATTRIBUTES_FK` FOREIGN KEY (`session_primary_id`) REFERENCES `spring_session` (`primary_id`))
      	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117) ~[mysql-connector-j-8.0.32.jar:8.0.32]
      	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.0.32.jar:8.0.32]
      	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[mysql-connector-j-8.0.32.jar:8.0.32]
      	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061) ~[mysql-connector-j-8.0.32.jar:8.0.32]
      	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009) ~[mysql-connector-j-8.0.32.jar:8.0.32]
      	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320) ~[mysql-connector-j-8.0.32.jar:8.0.32]
      	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994) ~[mysql-connector-j-8.0.32.jar:8.0.32]
      	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-5.0.1.jar:na]
      	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-5.0.1.jar:na]
      	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$2(JdbcTemplate.java:965) ~[spring-jdbc-6.0.6.jar:6.0.6]
      	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651) ~[spring-jdbc-6.0.6.jar:6.0.6]
      	... 14 common frames omitted

**Comment by emmanuelU17** [comment]
Got the issue solved

**Comment by Ingcamilo890604** [comment]
> Got the issue solved

how did you solve it?

**Comment by emmanuelU17** [comment]
> > Got the issue solved
> 
> 
> 
> how did you solve it?

Look in AuthService in my repo. https://github.com/emmanuelU17/session-authentication

**Comment by ufo525** [comment]
the validateMaxSession will not work if the 2 login requests arrives concurrently. The check will return empty list for both requests and a new session created for each request.
