### ISSUE TITLE
OAuth2AuthorizationCodeGrantFilter erroneously consumes POST request body with multipart/form-data

### ISSUE THREAD

**Issue by LaCoCa** [spring-projects/spring-security#15397]
Hi,

This part (request.getParameterMap()) consume the request body from POST request where we have multipart/form-data:

MultiValueMap<String, String> params = OAuth2AuthorizationResponseUtils.toMultiMap(request.getParameterMap());

Into filter code:

	@Override
	protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
			throws ServletException, IOException {
		if (matchesAuthorizationResponse(request)) {
			processAuthorizationResponse(request, response);
			return;
		}
		filterChain.doFilter(request, response);
	}

	private boolean matchesAuthorizationResponse(HttpServletRequest request) {
		MultiValueMap<String, String> params = OAuth2AuthorizationResponseUtils.toMultiMap(request.getParameterMap());
		if (!OAuth2AuthorizationResponseUtils.isAuthorizationResponse(params)) {
			return false;
		}

Could you help me with this issue?

More info:

My security config:

      config.oauth2Client(oauth2 -> oauth2
        .authorizationCodeGrant(codeGrant -> codeGrant
          .accessTokenResponseClient(this.accessTokenResponseClient())
        )
      );

Here is the part of the stack, before my service, which consume multipart/form-data:

        at org.springframework.security.oauth2.client.web.**OAuth2AuthorizationCodeGrantFilter**.doFilterInternal(OAuth2AuthorizationCodeGrantFilter.java:168) ~[spring-security-oauth2-client-5.7.6.jar:5.7.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.24.jar:5.3.24]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.6.jar:5.7.6]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109) ~[spring-security-web-5.7.6.jar:5.7.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.6.jar:5.7.6]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) ~[spring-security-web-5.7.6.jar:5.7.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.6.jar:5.7.6]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.7.6.jar:5.7.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.6.jar:5.7.6]
        at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:147) ~[spring-security-web-5.7.6.jar:5.7.6]
        at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:125) ~[spring-security-web-5.7.6.jar:5.7.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.6.jar:5.7.6]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:223) ~[spring-security-web-5.7.6.jar:5.7.6]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217) ~[spring-security-web-5.7.6.jar:5.7.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.6.jar:5.7.6]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214) ~[spring-security-web-5.7.6.jar:5.7.6]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:181) ~[spring-security-web-5.7.6.jar:5.7.6]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.6.jar:5.7.6]
        at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:178)

**Comment by sjohnr** [comment]
@LaCoCa thanks for reaching out!

I'm unable to determine if there's truly an issue from the information provided. I do see the use of `request.getParameterMap()` but have not seen an issue with this filter before. Please provide a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) so I can look further into this issue.

**Comment by LaCoCa** [comment]
Hi,
Just create on rest service like:

  @PostMapping ("/svc/simple/post/request")
  public ResponseEntity<?> create (@RequestPart (value = "srb") @Valid SimpleRequestBody srb,
                                   @RequestPart(value = "uploadedFile", required = false) MultipartFile uploadedFile )
  {
    return ResponseEntity.status(CREATED).build();
  }

Request body bean:
public class SimpleRequestBody
{
  public SimpleRequestBody(String info)
  {
    this.info = info;
  }

  public SimpleRequestBody()
  {
  }

  private String info;

  public String getInfo()
  {
    return info;
  }

  public void setInfo(String info)
  {
    this.info = info;
  }
}

I upload 2 applications with names - AP1 and AP2|
The only difference is that AP2 use filter:

public class MySimpleFilter extends OncePerRequestFilter
{
  private String codeGrantBeanName;

  @Override
  protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException
  {

    final Map<String, String[]> mp = request.getParameterMap();




A look the result:

![image](https://github.com/user-attachments/assets/73f7048d-31f7-4040-8d1a-c379117192b7)

![image](https://github.com/user-attachments/assets/9e6703fc-346a-4853-90da-5a6460346a6d)

org.springframework.web.multipart.support.MissingServletRequestPartException: Required request part 'srb' is not present
        at org.springframework.web.multipart.support.RequestPartServletServerHttpRequest.<init>(RequestPartServletServerHttpRequest.java:73) ~[spring-web-5.3.24.jar:5.3.24]
        at org.springframework.web.servlet.mvc.method.annotation.RequestPartMethodArgumentResolver.resolveArgument(RequestPartMethodArgumentResolver.java:139) ~[spring-webmvc-5.3.24.jar:5.3.24]
        at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:122) ~[spring-web-5.3.24.jar:5.3.24]
        at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:179) ~[spring-web-5.3.24.jar:5.3.24]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:146) ~[spring-web-5.3.24.jar:5.3.24]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.24.jar:5.3.24]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.24.jar:5.3.24]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.24.jar:5.3.24]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.24.jar:5.3.24]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071) ~[spring-webmvc-5.3.24.jar:5.3.24]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964) ~[spring-webmvc-5.3.24.jar:5.3.24]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.24.jar:5.3.24]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.24.jar:5.3.24]

**Comment by sjohnr** [comment]
@LaCoCa I have attempted to reproduce the issue using the provided REST controller method (`POST /svc/simple/post/request`) and postman. I made sure the `OAuth2AuthorizationCodeGrantFilter` was in the filter chain via `http.oauth2Client()`. However, I am unable to reproduce the issue. Please consider providing a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example), or this issue will be closed.

**Comment by LaCoCa** [comment]
@sjohnr I already show you with examples and workaround. 
Can you show me screenshots from your test in postman ?

**Comment by sjohnr** [comment]
I am closing this issue as unable to reproduce. If you are able to provide a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue, we can reopen and investigate further.

**Comment by LaCoCa** [comment]
@sjohnr
Can you show me screenshots from your test in postman ?

**Comment by jgrandja** [comment]
@LaCoCa It is standard process to provide a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue if you feel this is a bug. Showing screenshots in Postman is inefficient and results in lost time on both ends without getting to the root issue.

We will wait for the minimal sample that reproduces the issue so that we can efficiently troubleshoot.

**Comment by stefan1207** [comment]
I have the same issue in my application. The OAuth2AuthorizationCodeGrantFilter consumes input stream when reading parameters (incl. all parts!). I use the following option in my application.yml to avoid parsing before invoking my code:

`  servlet:
    multipart:
      resolve-lazily: true`

**Comment by LaCoCa** [comment]
@stefan1207 I made fix as create simple filter like:
`public class SkipOAuth2CodeGrantFilter extends OncePerRequestFilter
{
  private String codeGrantBeanName;

  @Override
  protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException
  {
    if (StringUtils.isNotEmpty(codeGrantBeanName) && RequestMethod.POST.name().equals(request.getMethod())) {
      if (StringUtils.containsAny(request.getContentType(), MULTIPART_FORM_DATA_VALUE)) {
        request.setAttribute(codeGrantBeanName + ALREADY_FILTERED_SUFFIX, "true");
      }
    }
    filterChain.doFilter(request, response);
  }

  public void setCodeGrantBeanName(String codeGrantBeanName)
  {
    this.codeGrantBeanName = codeGrantBeanName;
  }
}`
