### ISSUE TITLE
[Azure Oauth2] IllegalArgumentException: Attribute value for "xxx" is null

### ISSUE THREAD

**Issue by jloisel** [spring-projects/spring-security#16340]
Hi,

We are having the following issue when trying to configure Azure SSO Authentication using Spring Security Oauth2:

> { json: { log: "2024-12-20 12:42:53,285 [http-nio-8090-exec-40] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception java.lang.IllegalArgumentException: Attribute value for 'preferred_username' cannot be null at org.springframework.util.Assert.notNull(Assert.java:181) at org.springframework.security.oauth2.core.user.DefaultOAuth2User.<init>(DefaultOAuth2User.java:72) at org.springframework.security.oauth2.client.userinfo.DefaultOAuth2UserService.loadUser(DefaultOAuth2UserService.java:99) at org.springframework.security.oauth2.client.oidc.userinfo.OidcUserService.loadUser(OidcUserService.java:115) at org.springframework.security.oauth2.client.oidc.userinfo.OidcUserService.loadUser(OidcUserService.java:68) at org.springframework.security.oauth2.client.oidc.authentication.OidcAuthorizationCodeAuthenticationProvider.authenticate(OidcAuthorizationCodeAuthenticationProvider.java:158) at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182) at org.springframework.security.authentication.ObservationAuthenticationManager.lambda$authenticate$1(ObservationAuthenticationManager.java:54) at io.micrometer.observation.Observation.observe(Observation.java:565) at org.springframework.security.authentication.ObservationAuthenticationManager.authenticate(ObservationAuthenticationManager.java:53) at org.springframework.security.oauth2.client.web.OAuth2LoginAuthenticationFilter.attemptAuthentication(OAuth2LoginAuthenticationFilter.java:196) at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:231) at 

Seems linked to #15338.

If we use "sub" username attribute, there is no longer the issue (but sub cannot be mapped to an email on our system), but we can dump the user in an `Oauth2AuthenticationSuccessHandler`:

> 2024-12-20 08:19:46,820 [http-nio-8090-exec-7] ERROR - attrs={sub=xxxxxxx, ver=2.0, iss=https://login.microsoftonline.com/xxxxxx/v2.0, oid=xxxxx, preferred_username=[username@mail.com](mailto:username@mail.com), uti=xxxxxx, given_name=John, nonce=xxxx, picture=https://graph.microsoft.com/v1.0/me/photo/$value, tid=xxxxxx, aud=[xxxx], nbf=Fri Dec 20 08:14:45 UTC 2024, rh=xxxx, name=John Smith, exp=2024-12-20T09:19:45Z, family_name=Smith, iat=2024-12-20T08:14:45Z, email=[username@mail.com](mailto:username@mail.com)}

The claims have "preferred_username" in `Oauth2AuthenticationSuccessHandler` but if we use any as `user-name-attribute` it fails with a null pointer exception (despite being in the user claims afterwards).

I believe the null check is done too early and claims seem to be filled afterwards.

We are using Spring Security 6.4.2, Spring Boot 3.4.1.

**Comment by jloisel** [comment]
Code failing on Spring Security side:

```java
	public DefaultOAuth2User(Collection<? extends GrantedAuthority> authorities, Map<String, Object> attributes,
			String nameAttributeKey) {
		Assert.notEmpty(attributes, "attributes cannot be empty");
		Assert.hasText(nameAttributeKey, "nameAttributeKey cannot be empty");
		Assert.notNull(attributes.get(nameAttributeKey),
				"Attribute value for '" + nameAttributeKey + "' cannot be null");

		this.authorities = (authorities != null)
				? Collections.unmodifiableSet(new LinkedHashSet<>(this.sortAuthorities(authorities)))
				: Collections.unmodifiableSet(new LinkedHashSet<>(AuthorityUtils.NO_AUTHORITIES));
		this.attributes = Collections.unmodifiableMap(new LinkedHashMap<>(attributes));
		this.nameAttributeKey = nameAttributeKey;
	}
```

If we use "sub" as name attribute key, we are able to proceed further into our `Oauth2AuthenticationSuccessHandler` and log all user attributes:

```java
  @Override
  public void onAuthenticationSuccess(
    final HttpServletRequest request,
    final HttpServletResponse response,
    final Authentication authentication) throws IOException {

    final OAuth2AuthenticationToken token = (OAuth2AuthenticationToken) authentication;
    final String registrationId = token.getAuthorizedClientRegistrationId();
    final OAuth2User p = token.getPrincipal();

    
    
    final Pair<String, String> pair = repository.getUsernameSuffixAndAllowedDomains(registrationId);
    final String username = lowerCase(getUsername(p, pair.getKey()));

    log.error(
      "[SSO] Domain not allowed - id='{}', username='{}', attrs='{}', domains='{}'",
      registrationId, username, p.getAttributes(), allowedDomains
    );
....
}
```

Where we can see that all attributes are there:
> 2024-12-20 08:19:46,820 [http-nio-8090-exec-7] ERROR - attrs={sub=xxxxxxx, ver=2.0, iss=https://login.microsoftonline.com/xxxxxx/v2.0, oid=xxxxx, preferred_username=[username@mail.com](mailto:username@mail.com), uti=xxxxxx, given_name=John, nonce=xxxx, picture=https://graph.microsoft.com/v1.0/me/photo/$value, tid=xxxxxx, aud=[xxxx], nbf=Fri Dec 20 08:14:45 UTC 2024, rh=xxxx, name=John Smith, exp=2024-12-20T09:19:45Z, family_name=Smith, iat=2024-12-20T08:14:45Z, email=[username@mail.com](mailto:username@mail.com)}

**Comment by jloisel** [comment]
I have more info about the issue after debugging.

The issue is in `OidcUserService`:

```java
@Override
	public OidcUser loadUser(OidcUserRequest userRequest) throws OAuth2AuthenticationException {
		Assert.notNull(userRequest, "userRequest cannot be null");
		OidcUserInfo userInfo = null;
		if (this.retrieveUserInfo.test(userRequest)) {
			OAuth2User oauth2User = this.oauth2UserService.loadUser(userRequest);
			Map<String, Object> claims = getClaims(userRequest, oauth2User);
			userInfo = new OidcUserInfo(claims);
			// https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse
			// 1) The sub (subject) Claim MUST always be returned in the UserInfo Response
			if (userInfo.getSubject() == null) {
				OAuth2Error oauth2Error = new OAuth2Error(INVALID_USER_INFO_RESPONSE_ERROR_CODE);
				throw new OAuth2AuthenticationException(oauth2Error, oauth2Error.toString());
			}
			// 2) Due to the possibility of token substitution attacks (see Section
			// 16.11),
			// the UserInfo Response is not guaranteed to be about the End-User
			// identified by the sub (subject) element of the ID Token.
			// The sub Claim in the UserInfo Response MUST be verified to exactly match
			// the sub Claim in the ID Token; if they do not match,
			// the UserInfo Response values MUST NOT be used.
			if (!userInfo.getSubject().equals(userRequest.getIdToken().getSubject())) {
				OAuth2Error oauth2Error = new OAuth2Error(INVALID_USER_INFO_RESPONSE_ERROR_CODE);
				throw new OAuth2AuthenticationException(oauth2Error, oauth2Error.toString());
			}
		}
		return this.oidcUserMapper.apply(userRequest, userInfo);
	}
```

First, the Oauth2 user is created using `oauth2UserService`:

```java
OAuth2User oauth2User = this.oauth2UserService.loadUser(userRequest);
```

In this case, the user has only limited attributes (4 in our case, like "sub"). Later on:

```java
return this.oidcUserMapper.apply(userRequest, userInfo);
```

Which delegates to:

```java
org.springframework.security.oauth2.client.oidc.userinfo.OidcUserRequestUtils#getUser
```

This is where the `DefaultOidcUser` instance is created with all claims being available (coming from `OidcIdToken.getClaims()`).


The bug is in https://github.com/spring-projects/spring-security/blob/8e2a4bf3562133c78230ec5a96ec993c5c92374b/oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/user/DefaultOAuth2User.java#L72

```java
		Assert.notNull(attributes.get(nameAttributeKey),
				"Attribute value for '" + nameAttributeKey + "' cannot be null");
```

Checking for `nameAttributeKey` here is too early. The first `DefaultOauth2User` being created has not the `nameAttributeKey` claim populated at this point. The claims are available later when querying the userinfo endpoint. Later on, Spring Security re-creates an instance of `DefaultOidcUser` with all the claims populated.

The bug has been introduced in this commit:
https://github.com/spring-projects/spring-security/commit/e69e0eb245436733d803a37ac012ab89097689f5

This check cannot be performed this early.

**Comment by jloisel** [comment]
Associated pull request: #16546

**Comment by sjohnr** [comment]
@jloisel thanks for following up on this, and apologies that we didn't see this earlier. 

> This bug is preventing us from using Oauth2 authentication. I suspect it's breaking any oauth2 integration which has the username-attribute claim provided by the userinfo endpoint. Can you please take a look?

I have personally used the `user-name-attribute` with (for example) Auth0. It does work in that case. It sounds like the difference with Azure is that the claim is not coming in the `id_token`.

Can you please put together a minimal reproducer that includes your Spring Security `@Configuration` and any `application.yml` or properties for Spring Boot (with any credentials removed)? This will help me ensure I have your exact client-side setup. I can then set up a test with the SSO provider to reproduce.

**Comment by jloisel** [comment]
Hi,

I understand you are probably quite busy! You will have to find a provider which doesn't provide the user-name-attribute in in the first claims. I don't know which other SSO provider works that way. We also have a Google SSO integration and this one works well (but all claims are provided by the first call). 

You don't even need any specific Spring Security configuration. You can use a sample SSO, as long as you use Azure SSO (maybe other SSO providers working same way as Azure are broken too).

application.yml: (use your own clientId / clientSecret and TENANT_ID)
```yml
    spring.security.oauth2.client:
      registration:
        azure:
          client-id: XXX
          client-secret: XXX
          name: "Azure"
          scope: openid,profile,email
          client-authentication-method: client_secret_basic
          authorization-grant-type: authorization_code
          redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          client-name: azure
      provider:
        azure:
          authorization-uri: "https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/authorize"
          token-uri: "https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/token"
          user-info-uri: "https://graph.microsoft.com/oidc/userinfo"
          jwk-set-uri: "https://login.microsoftonline.com/TENANT_ID/discovery/v2.0/keys"
          issuer-uri: "https://login.microsoftonline.com/TENANT_ID/v2.0"
          user-name-attribute: preferred_username
```

**Comment by sjohnr** [comment]
> You will have to find a provider which doesn't provide the user-name-attribute in in the first claims.

If I can't get a developer account, I often just write integrations tests or customize Spring Authorization Server to emulate the misbehaving or problematic provider. I can handle that no problem. Thanks for the config.

**Comment by jloisel** [comment]
Hi @sjohnr 

Do you have any update on this issue?

Regards,

**Comment by sjohnr** [comment]
Not yet @jloisel. I will add this to my list for this week and see if I can look into it.

**Comment by sjohnr** [comment]
Hi @jloisel, I have not attempted to test Azure directly, but I have a test set up with Spring Authorization Server and I can easily reproduce. The way I reproduced the issue was to ensure that the ID Token contains an `preferred_username` claim, but only request `openid` and `email` scopes. In that case, the UserInfo Endpoint would not return the `preferred_username` claim (despite it being in the ID token claims), resulting in the error you are seeing.

The `preferred_username` claim comes as part of the `profile`. I see that you have requested both `profile` and `email` scopes, which means both `preferred_username` and `email` claims should be present in the UserInfo response. However, you seem to be reporting that Azure is not returning the `preferred_username` claim. Can you please confirm that this is the case?

Have you tried setting `user-name-attribute: email` instead? Do you have the same issue if you do this?

**Comment by jloisel** [comment]
Hi,

We have used "email" as well and it doesn't work, because Azure returns it via userinfo claims. Only "sub" attribute works, but it's an internal azure id which cannot be used as the username. Anything else fails with a null pointer.

**Comment by sjohnr** [comment]
> We have used "email" as well and it doesn't work, because Azure returns it via userinfo claims.

I think that would mean that it is **not returned** from the UserInfo endpoint. This would mean that Azure's UserInfo Endpoint is not spec-compliant.

Can you try something else for me? Please try commenting out the `user-info-uri` property so that the UserInfo endpoint is not called as part of the flow. If that doesn't work, you can also try removing `email` and `profile` from `scope`, which should also prevent the UserInfo endpoint from being called. Please let me know if either of those workarounds has any effect.

**Comment by jloisel** [comment]
We had initially setup the sso integration with openid scope only. But, as it contained only cryptic fields like "sub", we could not map any of the fields to a valid username. We added email and profile scopes later on, with the result described before.

The userinfo endpoint being called is not the issue. It provides the correct and meaningful claims later on if we configure "user-name-attribute" with a claim such as "sub" (we did this trying to find out workarounds). It's just too late because Spring fails much earlier when trying to instantiate `DefaultOauth2User` and fails to find the user-name-attribute in the minimal claims.

I'm not sure what else I can do to convince you it's simply not working the way it's coded as of now. If the user-name-attribute claim is only provided by the userinfo endpoint, Spring fails with an NPE before getting to call the userinfo endpoint.

**Comment by sjohnr** [comment]
> Spring fails much earlier when trying to instantiate `DefaultOauth2User` and fails to find the user-name-attribute in the minimal claims.

The `DefaultOAuth2User` class is used to contain the claims from the UserInfo response. So it is in fact the UserInfo that is returning the minimal claims, which is missing `preferred_username`. It is instantiated first, which is why you see this error happening earlier.

> The userinfo endpoint being called is not the issue. It provides the correct and meaningful claims later on if we configure "user-name-attribute" with a claim such as "sub" (we did this trying to find out workarounds).

The ID token contains the claims you are talking about here. Claims from both UserInfo and the ID token are later combined to create a `DefaultOidcUser`.

Please try the suggested workaround 

> Please try commenting out the user-info-uri property so that the UserInfo endpoint is not called as part of the flow.

and report back. I want to make sure I understand how the provider is behaving, as that is critical information for determining how to proceed.

**Comment by jloisel** [comment]
Hi,

I have tested the following:

- No userinfo endpoint provided, `preferred_username` as user-name-attribute` with just "openid" scope:

```
java.lang.IllegalArgumentException: Attribute value for 'preferred_username' cannot be null
	at org.springframework.util.Assert.notNull(Assert.java:181)
	at org.springframework.security.oauth2.core.user.DefaultOAuth2User.<init>(DefaultOAuth2User.java:72)
	at org.springframework.security.oauth2.core.oidc.user.DefaultOidcUser.<init>(DefaultOidcUser.java:97)
	at org.springframework.security.oauth2.client.oidc.userinfo.OidcUserRequestUtils.getUser(OidcUserRequestUtils.java:94)
	at org.springframework.security.oauth2.client.oidc.userinfo.OidcUserService.loadUser(OidcUserService.java:136)
	at org.springframework.security.oauth2.client.oidc.userinfo.OidcUserService.loadUser(OidcUserService.java:68)
	at org.springframework.security.oauth2.client.oidc.authentication.OidcAuthorizationCodeAuthenticationProvider.authenticate(OidcAuthorizationCodeAuthenticationProvider.java:158)
```

Here is a screenshot debugging the claims just before it throws the NPE:

![Image](https://github.com/user-attachments/assets/d182f54e-8314-4584-a71b-714b86394813)

- Now, set "preferred_username" as user-name-attribute, set again userinfo endpoint and "openid" scope, still failing with NPE:

![Image](https://github.com/user-attachments/assets/65770920-5b72-4aae-9c82-ef43f4847839)

![Image](https://github.com/user-attachments/assets/bcab301e-ed85-4950-8cee-a025053181e0)

- Testing with "sub" username attribute, openid,email,profile scopes and userinfo endpoint:

First stack:
```
<init>:71, DefaultOAuth2User (org.springframework.security.oauth2.core.user)
loadUser:99, DefaultOAuth2UserService (org.springframework.security.oauth2.client.userinfo)
loadUser:115, OidcUserService (org.springframework.security.oauth2.client.oidc.userinfo)
loadUser:68, OidcUserService (org.springframework.security.oauth2.client.oidc.userinfo)
authenticate:158, OidcAuthorizationCodeAuthenticationProvider (org.springframework.security.oauth2.client.oidc.authentication)
authenticate:182, ProviderManager (org.springframework.security.authentication)
lambda$authenticate$1:54, ObservationAuthenticationManager (org.springframework.security.authentication)
get:-1, ObservationAuthenticationManager$$Lambda$2469/0x00007a0718cf1800 
....
```

![Image](https://github.com/user-attachments/assets/bfe3c62e-8a50-4d22-b382-5c0ad0a23e82)

On second instantiation (withint the same flow of execution, later on), stack:

```
<init>:71, DefaultOAuth2User (org.springframework.security.oauth2.core.user)
<init>:97, DefaultOidcUser (org.springframework.security.oauth2.core.oidc.user)
getUser:94, OidcUserRequestUtils (org.springframework.security.oauth2.client.oidc.userinfo)
apply:-1, OidcUserService$$Lambda$1831/0x00007a0718ae6620 (org.springframework.security.oauth2.client.oidc.userinfo)
loadUser:136, OidcUserService (org.springframework.security.oauth2.client.oidc.userinfo)
loadUser:68, OidcUserService (org.springframework.security.oauth2.client.oidc.userinfo)
authenticate:158, OidcAuthorizationCodeAuthenticationProvider (org.springframework.security.oauth2.client.oidc.authentication)
authenticate:182, ProviderManager (org.springframework.security.authentication)
lambda$authenticate$1:54, ObservationAuthenticationManager (org.springframework.security.authentication)
get:-1, ObservationAuthenticationManager$$Lambda$2469/0x00007a0718cf1800 
....
```

![Image](https://github.com/user-attachments/assets/7db44280-b76a-4ee8-804d-963dfed8476b)

It does not fail NPE as "sub" is there on first instantiation, but not usable as a valid username.

When userinfo endpoint is provided, and scopes include "email,profile", then "preferred_username" is present the second time Spring instantiates the DefaultOauth2User. But, the first time, when the minimal Default2OauthUser is instantiated, the claim is not there.

**Comment by sjohnr** [comment]
Thanks @jloisel. Unfortunately, the combination I had hoped for, you have not tested yet according to the above. Apologies if I was unclear.

Please try commenting out the `user-info-uri` property but leave the `scope` as `openid,email,profile` and `user-name-attribute` as `preferred_username`. I can see based on your 2nd experiment that this will work, but want to make sure you can report that it works end-to-end in that case.

**Comment by sjohnr** [comment]
Thanks for confirming that works, @jloisel. We at least have a workaround to provide.

> I guess we can close the issue as it's a misconfiguration from our side.

I don't actually think it is a misconfiguration on your part. The issue is that Microsoft publishes the UserInfo Endpoint URI (`userinfo_endpoint`) as part of the well-known OpenID Provider Configuration Response (`.../v2.0/.well-known/openid-configuration`). So when just providing an `issuer-uri`, the application will actually be auto-configured as it is in your configuration example. I would expect other users to run into this as well.

To go any farther, I wanted to make sure I fully understood the provider behavior. One last question I have about that (as I don't have access to an environment I can look at for this information): Do you know of any configuration on the Azure side that would adjust the response for the UserInfo Endpoint? Meaning, is the behavior we're seeing here specific to your configuration, or are you using a generic environment and this behavior (missing claims in the UserInfo response) would be universal across environments?

**Comment by jloisel** [comment]
I don't know how Azure SSO is configured as one of our client did the configuration. They didn't indicate any special configuration from their side. We just got client id and secret from them. I used the well-known open-id configuration to manually configure the sso configuration on our side.

I don't think the issue here is specific to our configuration. We use spring boot oauth2 authentication without any customisation for our third party SSO integrations. It can be worth documenting this odd behavior and suggest to users stuck with the same issue to try removing the `user-info-uri`.

What was misleading was the fact changing the `user-name-attribute` to `sub` somehow "solved" the issue and we could see a `DefaultOauth2User` with all the claims (including `preferred_username`) reaching our implementation of `Oauth2AuthenticationSuccessHandler`.

I would expect other users to run into this issue as well.

**Comment by sjohnr** [comment]
Thanks @jloisel. I have created an Azure AD B2C tenant on a trial account to test whether this is an out-of-the-box experience. It appears that the UserInfo Endpoint from Microsoft Graph API always behaves this way by default. While it is possible to [customize the UserInfo Endpoint](https://learn.microsoft.com/en-us/azure/active-directory-b2c/userinfo-endpoint?pivots=b2c-custom-policy) as part of a custom policy, I doubt that's a viable option in general.

I'm not yet certain of a minimal fix for this issue in the framework. I'm going to leave this issue open to document [the workaround](https://github.com/spring-projects/spring-security/issues/16340#issuecomment-2748502743) (there are also other possible workarounds) while thinking of a solution.

**Comment by sjohnr** [comment]
@jloisel I've opened gh-16843 to track a possible enhancement for Spring Security 7. That enhancement would address this issue, but is a breaking change. We are considering whether this is the right direction to go in 7, or if there are other alternatives. I'm not aware of any alternatives at the moment.

**Comment by jloisel** [comment]
Thanks for the insight! The workaround is working in our situation.

**Comment by 1237633** [comment]
Had the same problem, while learning Spring Security Oauth. Self-made "client" was just redirecting me back to auth page and had IllegalArgumentException: Attribute value for "id" is null. I just added claim"id" with username as a value on Oauth server side and everything worked fine.

**Comment by jgrandja** [comment]
@jloisel I've read through all the comments in this issue and unfortunately I'm not able to reproduce your issue. I understand you have a workaround by [excluding the user-info-uri](https://github.com/spring-projects/spring-security/issues/16340#issuecomment-2750313269) attribute but I'm still trying to determine if there is a bug or if this issue can be closed.

What would be helpful to determine if a fix is required is if you can provide a test that reproduces your issue. You can use `OidcUserServiceTests.loadUserWhenStandardScopesAuthorizedThenUserInfoEndpointRequested()` as a starting template and adjust to your use case.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
