### ISSUE TITLE
SEC-1886: UnsupportedOperationException is thrown by DefaultFilterChainValidator if voter invokes an unsupported method

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2114]
[Kyle Cronin](https://jira.spring.io/secure/ViewProfile.jspa?name=kyle.cronin) (Migrated from [SEC-1886](https://jira.spring.io/browse/SEC-1886?redirect=false)) said:

The DefaultFilterChainValidator prevents the application context from starting up if a custom AccessDecisionVoter attempts to access an unsupported method of the DummyRequest, for example the #getRemoteAddr(). There is no way to turn off this validation when using <http> config.

```
Caused by: java.lang.UnsupportedOperationException
    at org.springframework.security.web.DummyRequest.getRemoteAddr(FilterInvocation.java:358)
    at com.foo.security.vote.IPRestrictionAccessVoter.vote(IPRestrictionAccessVoter.java:80)
    at com.foo.security.vote.IPRestrictionAccessVoter.vote(IPRestrictionAccessVoter.java:37)
    at org.springframework.security.access.vote.UnanimousBased.decide(UnanimousBased.java:77)
    at org.springframework.security.config.http.DefaultFilterChainValidator.checkLoginPageIsntProtected(DefaultFilterChainValidator.java:170)
    at org.springframework.security.config.http.DefaultFilterChainValidator.validate(DefaultFilterChainValidator.java:35)
    at org.springframework.security.web.FilterChainProxy.afterPropertiesSet(FilterChainProxy.java:148)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1514)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1452)
    ... 155 more
```

**Comment by spring-issuemaster** [comment]
This issue duplicates #2106
