### ISSUE TITLE
SEC-1920: Make it easier to customize SessionManagementFilter

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2147]
[Ludovic Claude](https://jira.spring.io/secure/ViewProfile.jspa?name=ludovicc) (Migrated from [SEC-1920](https://jira.spring.io/browse/SEC-1920?redirect=false)) said:

I have a website sitting behind a load-balancer, and it needs to support multiple tenancy (different DNS names can be used on the Net, but the same web server will be used, with different configuration depending on the DNS name). Plus, the load balancer does HTTPS to HTTP translation. All those requirements make it very difficult to deal with redirects in my application. To deal with that, I have written a custom RedirectStrategy. Unfortunately, Spring makes it so difficult to change the DefaultRedirectStrategy to anything custom. I have customize all the success handler, failure handlers and such. Now is the turn of SessionManagementFilter. Here's what I do:

	@Bean
	@Scope("singleton")
	SessionManagementFilter sessionManagementFilter() {
		SessionFixationProtectionStrategy sessionFixationPS = new SessionFixationProtectionStrategy();
		SessionManagementFilter filter = new SessionManagementFilter(securityContextRepository, sessionFixationPS);
		filter.setInvalidSessionStrategy(new AbsoluteRedirectInvalidSessionStrategy("/public/invalid_session"));
		filter.setAuthenticationFailureHandler(authenticationFailureHandler());
		return filter;
	}

    <security:http use-expressions="true" auto-config="false" create-session="always" entry-point-ref="loginUrlAuthenticationEntryPoint">
        <security:custom-filter position="PRE_AUTH_FILTER" ref="casinoSSOSecurityFilter" />
        <security:custom-filter position="FORM_LOGIN_FILTER" ref="casinoAuthenticationProcessingFilter" />
        <security:custom-filter position="LOGOUT_FILTER" ref="logoutFilter" />
        <security:custom-filter position="SESSION_MANAGEMENT_FILTER" ref="sessionManagementFilter" />
    [...]

When I start the application, it fails with this error:

org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Filter beans '<sessionManagementFilter>' and 'Root bean: class [org.springframework.security.web.session.SessionManagementFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null' have the same 'order' value. When using custom filters, please make sure the positions do not conflict with default filters. Alternatively you can disable the default filters by removing the corresponding child elements from <http> and avoiding the use of <http auto-config='true'>.|Offending resource: class path resource [META-INF/spring/applicationContext-security.xml]
	at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:68)
	at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:85)
	at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:72)
	at org.springframework.security.config.http.HttpSecurityBeanDefinitionParser.checkFilterChainOrder(HttpSecurityBeanDefinitionParser.java:237)
	at org.springframework.security.config.http.HttpSecurityBeanDefinitionParser.createFilterChain(HttpSecurityBeanDefinitionParser.java:132)
	at org.springframework.security.config.http.HttpSecurityBeanDefinitionParser.parse(HttpSecurityBeanDefinitionParser.java:81)
	at org.springframework.security.config.SecurityNamespaceHandler.parse(SecurityNamespaceHandler.java:88)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1419)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1409)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:184)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:140)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:111)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:493)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:390)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:334)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:209)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromImportedResources(ConfigurationClassBeanDefinitionReader.java:303)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:131)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:118)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:294)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:203)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:617)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:446)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:385)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:284)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)

I have set <http auto-config='false'> and there is no <security:session-management> tag in my XML configuration, yet it fails...

**Comment by TeHMoroS** [comment]
Hi.

There is a way of handling this. After analyzing the SessionManagementConfigurer I've came up with a simple workaround. The example that I'm showing below is based on a non-String-Boot application with Java configuration (no XML).

The security config (relevant parts only):
```java

    @Autowired
    private SessionManagementFilterPostProcessor sessionManagementFilterPostProcessor;

    @Override
    protected void configure(HttpSecurity http) throws Exception {
(...)
        http.sessionManagement().withObjectPostProcessor(sessionManagementFilterPostProcessor)
                .sessionCreationPolicy... (the configuration continued...)
(...)
    }
```

SessionManagementFilterPostProcessor:
```java
@Component
public class SessionManagementFilterPostProcessor implements ObjectPostProcessor<SessionManagementFilter> {

    @Autowired
    private CustomAuthenticationFailureHandler authenticationFailureHandler;

    @Override
    public <O extends SessionManagementFilter> O postProcess(O object) {
        object.setAuthenticationFailureHandler(authenticationFailureHandler);
        return object;
    }
}
```

In this example I set a custom AuthenticationFailureHandler implementation, but you can pretty much modify anything that has a public setter method. It's quite easy and quick to implement.

How does it work? When you create your java config for Spring Sec session handling, you use the SessionManagementConfigurer. That configurer, before adding the SessionManagementFilter to the chain, runs a method called postProcess(), which launches any post-processors related to the class.

That way I was able to make Spring Sec return a HTTP 401 with JSON content instead of the default output when session concurrency conditions are violated.

Hope this will be of use to someone. :)

**Comment by rwinch** [comment]
This is not really something you should do within Spring Security. Instead, you should configure your application server to use X-Forwarded headers. 

* [Tomcat](https://tomcat.apache.org/tomcat-8.0-doc/api/org/apache/catalina/valves/RemoteIpValve.html)
* [Jetty](http://www.eclipse.org/jetty/documentation/current/configuring-connectors.html#d0e4413)
* Spring 4.3+ can use [ForwardedHeaderFilter](https://github.com/spring-projects/spring-framework/blob/v4.3.0.RC1/spring-web/src/main/java/org/springframework/web/filter/ForwardedHeaderFilter.java). See also [SPR-13614](https://jira.spring.io/browse/SPR-13614)
