### ISSUE TITLE
SEC-2604: Spring Security not working with configurations in Parent Application Contect

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2821]
[Amit Gadkari](https://jira.spring.io/secure/ViewProfile.jspa?name=amitashokgadkari) (Migrated from [SEC-2604](https://jira.spring.io/browse/SEC-2604?redirect=false)) said:

Hi,

In your web application, we have three layers of application context. 
1. Spring MVC Context
2. Web Application Context
3. Parent Application Context.

WebApplicationContext is parent of SpringMVCContext.
ParentApplicationContext is parent of WebApplicationContext.

We are using JavaConfig in our application.
Now, we want to use Authorization feature Spring Security in our application. To use this we configured below in Parent Context
1. Authentication Manager
2. Authentication Provider
3. UserDetailsService
We have defined these beans in the class which extends from GlobalSecurityConfiguration. This class is annotated with @GlobalMethodSecurity.
We've overriden the configure(AuthenticationManagerBuilder) and added AuthenticationProvider in AuthenticationBuilder to build the AuthenticationManager.

```
protected void configure(AuthenticationManagerBuilder auth) throws Exception {

        auth.authenticationProvider(preAuthenticatedAuthenticationProvider());

    }
```

We have exposed the AuthenticationManager as below

```
   @Bean(name="authenticationManager")
    public AuthenticationManager authenticationManagerBean() throws Exception {
        return authenticationManager();
    }
```

And, we have configured the required filter bean in SpringMVCContext. 
Filter gets the reference of the AuthenticationManager which is configured in ParentContext. However, it throws below exception and application does not work.

```
Caused by: java.lang.IllegalAccessError: org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration$LazyBean
      at java.lang.reflect.Proxy.defineClass0(Native Method)
      at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:625)
      at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:702)
      at org.springframework.aop.framework.JdkDynamicAopProxy.getProxy(JdkDynamicAopProxy.java:121)
      at org.springframework.aop.framework.ProxyFactoryBean.getProxy(ProxyFactoryBean.java:368)
      at org.springframework.aop.framework.ProxyFactoryBean.getSingletonInstance(ProxyFactoryBean.java:322)
      at org.springframework.aop.framework.ProxyFactoryBean.getObject(ProxyFactoryBean.java:246)
      at org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration.lazyBean(AuthenticationConfiguration.java:119)
      at org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration.getAuthenticationMangerBean(AuthenticationConfiguration.java:123)
      at org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration.getAuthenticationManager(AuthenticationConfiguration.java:81)
      at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter.authenticationManager(WebSecurityConfigurerAdapter.java:229)
      at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter.getHttp(WebSecurityConfigurerAdapter.java:171)
      at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter.init(WebSecurityConfigurerAdapter.java:276)
      at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter.init(WebSecurityConfigurerAdapter.java:61)
      at com.deere.dsfj.jdorderspringmvcweb.config.SpringWebSecurityConfig$$EnhancerBySpringCGLIB$$1ccbdc0f.init(<generated>)
      at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.init(AbstractConfiguredSecurityBuilder.java:369)
      at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.doBuild(AbstractConfiguredSecurityBuilder.java:322)
      at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:39)
      at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.springSecurityFilterChain(WebSecurityConfiguration.java:92)
      at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration$$EnhancerBySpringCGLIB$$a1372076.CGLIB$springSecurityFilterChain$1(<generated>)
      at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration$$EnhancerBySpringCGLIB$$a1372076$$FastClassBySpringCGLIB$$a530ca1c.invoke(<generated>)
      at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
      at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:312)
      at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration$$EnhancerBySpringCGLIB$$a1372076.springSecurityFilterChain(<generated>)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
      at java.lang.reflect.Method.invoke(Method.java:611)
      at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:166)
      ... 113 more
```

Please suggest

**Comment by spring-issuemaster** [comment]
This issue duplicates #2763
