### ISSUE TITLE
SEC-3160: Invalid HTTP verb throws 500 not 400

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3370]
[Kris](https://jira.spring.io/secure/ViewProfile.jspa?name=krism) (Migrated from [SEC-3160](https://jira.spring.io/browse/SEC-3160?redirect=false)) said:

Had a few cases of a bad client request which doesn't match a valid HTTP verb, i would expect this to be returned as a 400 Bad Request, instead our access log showed as a 500.

```
java.lang.IllegalArgumentException: No enum constant 
               at java.lang.Enum.valueOf(Enum.java:238)
                at org.springframework.http.HttpMethod.valueOf(HttpMethod.java:27)
                at org.springframework.security.web.util.matcher.AntPathRequestMatcher.matches(AntPathRequestMatcher.java:125)
                at org.springframework.security.web.access.intercept.DefaultFilterInvocationSecurityMetadataSource.getAttributes(DefaultFilterInvocationSecurityMetadataSource.java:86)
                at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:174)
                at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecur


```

**Comment by rwinch** [comment]
This issue duplicates #3054

**Comment by digitalserenity** [comment]
Yep thanks! Upgrading resolved
