### ISSUE TITLE
SEC-3208: Fast Login and Logout is causing an Exception on Wildfly 10

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3406]
[cns-web](https://jira.spring.io/secure/ViewProfile.jspa?name=cns-web) (Migrated from [SEC-3208](https://jira.spring.io/browse/SEC-3208?redirect=false)) said:

If i perform a login and a logout immediately after seeing the page again, the following exception happens. If i use JAAS authentication on WF (Without spring security everything is fine.)

``` java

09:49:22,760 ERROR [io.undertow.request] (default task-2) UT005023: Exception handling request to /portal/index.xhtml: java.lang.IllegalStateException: UT000010: Session not found jOisRdS2aXEfZKjA7ZVrrbStshpPlh7tgCCiW1m8
    at io.undertow.server.session.InMemorySessionManager$SessionImpl.getAttribute(InMemorySessionManager.java:464)
    at io.undertow.servlet.spec.HttpSessionImpl.getAttribute(HttpSessionImpl.java:123)
    at org.springframework.security.web.context.HttpSessionSecurityContextRepository$SaveToSessionResponseWrapper.saveContext(HttpSessionSecurityContextRepository.java:358)
    at org.springframework.security.web.context.HttpSessionSecurityContextRepository.saveContext(HttpSessionSecurityContextRepository.java:136)
    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:100)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

```

The login is done by using the 'DefaultJaasAuthenticationProvider' class. 

``` java

http.authorizeRequests().antMatchers("........").fullyAuthenticated().and().formLogin().loginPage("...........").and().csrf().disable().headers().frameOptions().disable();

```

This is the code i use to perform the logout 

``` java
    public static void logout(HttpServletRequest request, HttpServletResponse response) {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        SecurityContextLogoutHandler logoutHandler = new SecurityContextLogoutHandler();
        logoutHandler.logout(request, response, authentication);
    }

```

**Comment by bgiorgini** [comment]
We are facing same issue in Wildfly 10. Not able to reproduce, but it's very annoying because when it happens, it fills up all the logs with same exception.

**Comment by Noah1989** [comment]
I've seen this today with Wildfly 9.0.2.Final. This is really hard to reproduce and only happens a few times per year in our application.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
