### ISSUE TITLE
UpdateAcl cause DeadlockLoserDataAccessException

### ISSUE THREAD

**Issue by Hamouz** [spring-projects/spring-security#3806]
### Summary

when deleting permession i get deadlock exception
  at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:716)
        at org.springframework.security.acls.jdbc.JdbcAclService.findChildren(JdbcAclService.java:76)
        at org.springframework.security.acls.jdbc.JdbcMutableAclService.clearCacheIncludingChildren(JdbcMutableAclService.java:325)
        at org.springframework.security.acls.jdbc.JdbcMutableAclService.updateAcl(JdbcMutableAclService.java:317)
        at com.allence.commons.security.AclSecurityUtilImpl.deletePermission(AclSecurityUtilImpl.java:222)
        at com.allence.commons.security.AclSecurityUtilImpl.deletePermission(AclSecurityUtilImpl.java:198)
### Configuration

spring security version 3.1.4.RELEASE

**Comment by rwinch** [comment]
This doesn't provide enough information to reproduce the problem. I'm going to need more information or this will be closed

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
