### ISSUE TITLE
AuthenticationConfiguration.lazyBean(AuthenticationManager.class) should honor @Primary if multiple candidates are available

### ISSUE THREAD

**Issue by cheppsn** [spring-projects/spring-security#3912]
Using Spring Boot 1.3.4, Spring Security 4.0.4:

I encounter the following Exception for some (MockMvc) Tests that I want to run:

```
Caused by: java.lang.IllegalArgumentException: Expecting to only find a single bean for type interface org.springframework.security.authentication.AuthenticationManager, but found [docAuthenticationManager, webAuthenticationManager, globalAuthenticationManager]
    at org.springframework.util.Assert.isTrue(Assert.java:68)
    at org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration.lazyBean(AuthenticationConfiguration.java:116)
    at org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration.getAuthenticationMangerBean(AuthenticationConfiguration.java:128)
    at org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration.getAuthenticationManager(AuthenticationConfiguration.java:84)
    at org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration.authenticationManager(GlobalMethodSecurityConfiguration.java:257)
    at org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration.methodSecurityInterceptor(GlobalMethodSecurityConfiguration.java:123)
    at ch.belimo.cloud.server.services.security.SecurityConfiguration$MethodSecurityConfiguration$$EnhancerBySpringCGLIB$$8864b9ed.CGLIB$methodSecurityInterceptor$8(<generated>)
    at ch.belimo.cloud.server.services.security.SecurityConfiguration$MethodSecurityConfiguration$$EnhancerBySpringCGLIB$$8864b9ed$$FastClassBySpringCGLIB$$b67a6873.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
    at com.mystuff.SecurityConfiguration$MethodSecurityConfiguration$$EnhancerBySpringCGLIB$$8864b9ed.methodSecurityInterceptor(<generated
...
```

I tried to fix the issue by defining an `@Primary` annotated AuthenticationManager instance for my Test, but this has no effect. The reason being that the `AuthenticationConfiguration.lazyBean()` Method does not honor `@Primary`, if multiple candidates are found:

```
String[] beanNamesForType = BeanFactoryUtils.beanNamesForTypeIncludingAncestors(
            applicationContext, interfaceName);
    if (beanNamesForType.length == 0) {
        return null;
    }
    Assert.isTrue(beanNamesForType.length == 1,
            "Expecting to only find a single bean for type " + interfaceName
                    + ", but found " + Arrays.asList(beanNamesForType));
```

**Comment by rwinch** [comment]
Thanks for the report @cheppsn! I have scheduled this for 4.2 M1

**Comment by rwinch** [comment]
Dropping from 4.2 as we are keeping this release focused on community contributions so the team can get Spring Security 5.0 out
