### ISSUE TITLE
AuthenticationCredentialsNotFoundException - Multithreading problem?

### ISSUE THREAD

**Issue by silentsnooc** [spring-projects/spring-security#3919]
**Note:** I am asking this on stack**overflow** ([link](http://stackoverflow.com/questions/34273755/sometimes-getting-authenticationcredentialsnotfoundexception-between-multiple-re))

### Summary

It does not matter whether I am performing a login or if I am just accessing a method with `@PreAuthorize("isAuthenticated()")` present, I am sometimes getting a `AuthenticationCredentialsNotFoundException` and it appears to happen if there is some kind of thread-switch going on. In my debug output I am seeing that suddenly a different thread is taking over:

```
	[http-bio-8080-exec-4] INFO  com.mz.server.repository.jooq.shop.ShopAdminRepository - Checking password for user@gmx.at
	[http-bio-8080-exec-4] DEBUG com.mz.server.repository.jooq.shop.ShopAdminRepository - Password valid.
	[http-bio-8080-exec-4] DEBUG com.mz.server.spring.auth.CustomUserAuthentication - getPrincipal()
	[http-bio-8080-exec-4] DEBUG com.mz.server.spring.auth.CustomUserAuthentication - Setting user com.mz.server.spring.auth.ShopAdminUserDetails@8ac733b2: Username: user@gmx.at; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Not granted any authorities to 'authenticated'.
	[http-bio-8080-exec-4] INFO  com.mz.server.service.LoginService - User successfully authenticated [userEmail=user@gmx.at]
	[http-bio-8080-exec-4] DEBUG com.mz.server.repository.jooq.shop.ShopAdminRepository - findByUserEmail(): user@gmx.at
	[http-bio-8080-exec-4] DEBUG com.mz.server.repository.jooq.shop.ShopAdminRepository - User found.
	[http-bio-8080-exec-6] DEBUG com.mz.server.servlet.shop.ShopServletImpl - Requested available shops.
	[http-bio-8080-exec-6] INFO  com.mz.server.servlet.shop.ShopServletImpl - 
	[http-bio-8080-exec-6] INFO  com.mz.server.servlet.shop.ShopServletImpl - 
	[http-bio-8080-exec-6] INFO  com.mz.server.servlet.shop.ShopServletImpl - SPRING_SECURITY_CONTEXT: org.springframework.security.core.context.SecurityContextImpl@259bee56: Authentication: com.mz.server.spring.auth.CustomUserAuthentication@259bee56
	[http-bio-8080-exec-6] INFO  com.mz.server.servlet.shop.ShopServletImpl - 
	[http-bio-8080-exec-6] INFO  com.mz.server.servlet.shop.ShopServletImpl - 
	[http-bio-8080-exec-6] DEBUG org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor - Secure object: ReflectiveMethodInvocation: public java.util.List com.mz.server.service.ShopService.getAvailableShops(); target is of class [com.mz.server.service.ShopService]; Attributes: [[authorize: 'isAuthenticated()', filter: 'null', filterTarget: 'null']]
	[http-bio-8080-exec-6] DEBUG com.mz.server.spring.auth.CustomHttpSessionListener - AuthenticationCredentialsNotFoundEvent
	Jun 09, 2016 8:06:42 PM org.apache.catalina.core.ApplicationContext log
	SEVERE: Exception while dispatching incoming RPC call
	com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.util.List com.mz.shared.web.service.shop.ShopServlet.getAvailableShops()' threw an unexpected exception: org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
		at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:416)
		at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
		at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
		at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
		at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
```

### Actual Behavior

Observing my logging output I am seeing that every time threads are "switching" I am getting the said exception.

### Expected Behavior

Not getting the exception.

### Configuration

```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:security="http://www.springframework.org/schema/security"
	xmlns:p="http://www.springframework.org/schema/p" xmlns:jdbc="http://www.springframework.org/schema/jdbc"
	
	xmlns:sec="http://www.springframework.org/schema/security"
	
	xsi:schemaLocation="http://www.springframework.org/schema/beans 
		http://www.springframework.org/schema/beans/spring-beans-4.0.xsd
		http://www.springframework.org/schema/security 
		http://www.springframework.org/schema/security/spring-security-4.0.xsd
		http://www.springframework.org/schema/jdbc 
		http://www.springframework.org/schema/jdbc/spring-jdbc-4.0.xsd">
		
	<!-- Imports -->
	<import resource="applicationContext-jooq.xml"/>
	
	<sec:global-method-security authentication-manager-ref="authenticationManager" pre-post-annotations="enabled">   
    	<sec:expression-handler ref="expressionHandler"/>    	
    </sec:global-method-security>

	<!-- See 15.3.2 Built-In Expression @http://static.springsource.org/spring-security/site/docs/3.0.x/reference/el-access.html#el-permission-evaluator -->
	<bean id="expressionHandler" class="org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler">
		<!-- To use hasPermission() in expressions, configure a PermissionEvaluator -->
		<property name="permissionEvaluator" ref="permissionEvaluator" />
		<property name="roleHierarchy" ref="roleHierarchy" />
	</bean>	

	<bean id="permissionEvaluator" class="com.mz.server.spring.auth.permission.CustomAclPermissionEvaluator" >
		<constructor-arg ref="aclService" />
	</bean>
	
	<!-- Declare an acl service -->
	<bean id="aclService" class="org.springframework.security.acls.jdbc.JdbcMutableAclService" >
		<constructor-arg ref="dataSource" />
		<constructor-arg ref="lookupStrategy" />
		<constructor-arg ref="aclCache" />
	</bean>

	<!-- Declare a lookup strategy -->
	<bean id="lookupStrategy" class="org.springframework.security.acls.jdbc.BasicLookupStrategy">
		<constructor-arg ref="dataSource" />
		<constructor-arg ref="aclCache" />
		<constructor-arg ref="aclAuthorizationStrategy" />
		<constructor-arg ref="auditLogger" />
	</bean>

	<!-- Declare an acl cache -->
	<bean id="aclCache" class="org.springframework.security.acls.domain.EhCacheBasedAclCache">
		<constructor-arg>
			<bean class="org.springframework.cache.ehcache.EhCacheFactoryBean">
				<property name="cacheManager">
					<bean class="org.springframework.cache.ehcache.EhCacheManagerFactoryBean" p:shared="true"/>
				</property>
				<property name="cacheName" value="aclCache" />
			</bean>
		</constructor-arg>
		<constructor-arg>
			<bean class="org.springframework.security.acls.domain.DefaultPermissionGrantingStrategy">
				<constructor-arg>
					<bean class="org.springframework.security.acls.domain.ConsoleAuditLogger" />
				</constructor-arg>
			</bean>
		</constructor-arg>	
		<constructor-arg name="aclAuthorizationStrategy" ref="aclAuthorizationStrategy"></constructor-arg>
	</bean>

	<!-- Declare an acl authorization strategy -->
	<bean id="aclAuthorizationStrategy" class="org.springframework.security.acls.domain.AclAuthorizationStrategyImpl">
		<constructor-arg>
			<list>
				<bean class="org.springframework.security.core.authority.SimpleGrantedAuthority">
					<constructor-arg value="ROLE_ADMIN" />
				</bean>
			</list>
		</constructor-arg>
	</bean>

	<!-- Declare an audit logger -->
	<bean id="auditLogger" class="org.springframework.security.acls.domain.ConsoleAuditLogger" />

	<!-- http://static.springsource.org/spring-security/site/docs/3.0.x/apidocs/org/springframework/security/access/hierarchicalroles/RoleHierarchyImpl.html -->
	<bean id="roleHierarchy"
		class="org.springframework.security.access.hierarchicalroles.RoleHierarchyImpl">
		<property name="hierarchy">
			<value>
				ROLE_ADMIN > ROLE_USER
				ROLE_USER > ROLE_VISITOR
			</value>
		</property>
	</bean>
	
</beans>
```

### Version

Spring Framework: `4.2.3-RELEASE`
Spring Security: `4.0.3-RELEASE`

### More

I think I've found the answer to [this question of mine](http://stackoverflow.com/questions/34273755/why-is-the-authentication-object-of-the-securitycontext-not-shared-across-thread) but I am not yet sure how I'd have to use the class [`DelegatingSecurityContextRunnable`](http://docs.spring.io/autorepo/docs/spring-security/3.2.4.RELEASE/reference/htmlsingle/#delegatingsecuritycontextrunnable) in my application or if this is really **my** job or if Spring should actually do this for me in the background. I tend to believe that Spring should do this on its own but for some reason it doesn't work.

There is [this example](http://docs.spring.io/autorepo/docs/spring-security/3.2.4.RELEASE/reference/htmlsingle/#delegatingsecuritycontextrunnable) in the documentation that says that `DelegatingSecurityContextRunnable` does something like this:

```java
    public void run() {
        try {
            SecurityContextHolder.setContext(securityContext);
            delegate.run();
        } finally {
            SecurityContextHolder.clearContext();
        }
    }
```

and that this is how I'd use this to pass the context between threads:

```java
    Runnable originalRunnable = new Runnable() {
      public void run() {
        // invoke secured service
      }
    };

    DelegatingSecurityContextRunnable wrappedRunnable =
        new DelegatingSecurityContextRunnable(originalRunnable);
    
    new Thread(wrappedRunnable).start();
```
Okay, that's that. What do we see here.. 

This seems to pass the `SecurityContext` from the dispatched Servlet thread to another thread that does some asynchronous work. Very nice.

But why is Spring not doing this for me? As you can see in [this question of mine](http://stackoverflow.com/questions/34273755/why-is-the-authentication-object-of-the-securitycontext-not-shared-across-thread) I'm having the problem that if another thread is dispatched than the one that has logged in the user, the `SecurityContext` is not present and therefore giving me a `org.springframework.security.authentication.AuthenticationCredentialsNotFoundException`.

Any idea how I can fix this?

**Comment by silentsnooc** [comment]
It appears that I just configured it wrong. I think I got it working now. If you landed here because you're having the same issue and didn't see the link already, maybe take a look at [this](http://stackoverflow.com/questions/34273755/why-is-the-authentication-object-of-the-securitycontext-not-shared-across-thread).
