### ISSUE TITLE
Can @PreAuthorize expressions return a value of a type other than `boolean`?

### ISSUE THREAD

**Issue by lyubomyr-shaydariv** [spring-projects/spring-security#4006]
### Summary

I'm using the Spring Security framework `@PreAuthorize` annotation in order to apply some authorization checks for the methods of the REST controller I develop. All of the `@PreAuthorize`-annotated methods deal with `boolean` expressions, however for certain reasons I would like to make it work with custom types, say, a simple enum of `PASS`/`DENY` or a more complex objects.

### Actual Behavior

Trying to use an expression return type other than `boolean` causes the following exception:

```
java.lang.IllegalArgumentException: Failed to evaluate expression '@primaryAuth.authentication.mayReadMe(principal)'
    at org.springframework.security.access.expression.ExpressionUtils.evaluateAsBoolean(ExpressionUtils.java:15)
    at org.springframework.security.access.expression.method.ExpressionBasedPreInvocationAdvice.before(ExpressionBasedPreInvocationAdvice.java:44)
    at org.springframework.security.access.prepost.PreInvocationAuthorizationAdviceVoter.vote(PreInvocationAuthorizationAdviceVoter.java:57)
    at org.springframework.security.access.prepost.PreInvocationAuthorizationAdviceVoter.vote(PreInvocationAuthorizationAdviceVoter.java:25)
    at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:62)
    at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:232)
    at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:64)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
...
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1001E:(pos 0): Type conversion problem, cannot convert from @javax.annotation.Nonnull foo.bar.FooBarEnum to java.lang.Boolean
    at org.springframework.expression.spel.support.StandardTypeConverter.convertValue(StandardTypeConverter.java:78)
    at org.springframework.expression.common.ExpressionUtils.convertTypedValue(ExpressionUtils.java:53)
    at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:301)
    at org.springframework.security.access.expression.ExpressionUtils.evaluateAsBoolean(ExpressionUtils.java:11)
    ... 113 common frames omitted
Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [@javax.annotation.Nonnull foo.bar.FooBarEnum] to type [java.lang.Boolean]
    at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:313)
    at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:195)
    at org.springframework.expression.spel.support.StandardTypeConverter.convertValue(StandardTypeConverter.java:74)
    ... 116 common frames omitted
```
Trying to add a custom converter does not work for unknown reason.

### Expected Behavior

A `@PreAuthrorize` expression to work with any custom return types. Why:

* _To get more information about the authorization expression, and not its result only_
* _To invoke custom methods like `.toStringExpression` in order to build human-readable authorization rules available using my REST service_

### Configuration

What I've tried so far is:

* Adding converterters using `WebMvcConfigurerAdapter.addFormatters(FormatterRegistry)` (both `Converter` and `GenericConverter`) -- totally ignored
* Trying to bean a custom `PreInvocationAuthorizationAdvice` using `GlobalMethodSecurityConfiguration.preInvocationAuthorizationAdvice()` in order to add a custom type support -- totally ignored
* Trying to autowire a default conversion service (+ bean) to add a custom converter -- totaly ignored
* ... (and more as I've spent more than a day trying to implement it)

### Version

`org.springframework.security:spring-security-test:4.0.4.RELEASE`

### Sample

The configuration per se:

``` java
@Configuration
@EnableGlobalMethodSecurity(prePostEnabled = true, securedEnabled = true)
public class SecurityConfiguration
		extends GlobalMethodSecurityConfiguration {

// ...

	@Autowired
	private ApplicationContext context;

// ...

	@Override
	protected MethodSecurityExpressionHandler createExpressionHandler() {
		final PermissionEvaluator evaluator = getDefaultPermissionEvaluator();
		final DefaultMethodSecurityExpressionHandler handler = getCustomMethodSecurityExpressionHandler(...);
		handler.setPermissionEvaluator(evaluator);
		handler.setApplicationContext(context);
		return handler;
	}

// ...

}
```

I do not provide the implementation of test converters, since they are trivial (as far as I know) and get never invoked in context of the `@PreAuthorize` expression evaluation.

Can `@PreAuthorize` expressions return a value of a type other than `boolean`?

**Comment by lyubomyr-shaydariv** [comment]
Figured it out.  Just need to specify a custom type converter like this, where `ForwardingStandardEvaluationContext` is a custom forwarding-decorator:

```java
@Override
protected MethodSecurityExpressionHandler createExpressionHandler() {
	final ApplicationContext applicationContext = applicationContext();
	final TypeConverter typeConverter = new StandardTypeConverter(conversionService());
	final DefaultMethodSecurityExpressionHandler handler = new DefaultMethodSecurityExpressionHandler() {
		@Override
		public StandardEvaluationContext createEvaluationContextInternal(final Authentication authentication, final MethodInvocation methodInvocation) {
			final StandardEvaluationContext decoratedStandardEvaluationContext = super.createEvaluationContextInternal(authentication, methodInvocation);
			return new ForwardingStandardEvaluationContext() {
				@Override
				protected StandardEvaluationContext standardEvaluationContext() {
					return decoratedStandardEvaluationContext;
				}

				@Override
				public TypeConverter getTypeConverter() {
					return typeConverter;
				}
			};
		}
	};
	handler.setApplicationContext(applicationContext);
	return handler;
}
```

Apologies, it was much easier than I thought earlier.
