### ISSUE TITLE
SEC-143: NPE in JaasAuthenticationProvider

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#404]
["Eric Hedström":https://jira.spring.io/secure/ViewProfile.jspa?name=ehedstrom](Migrated from ["SEC-143":https://jira.spring.io/browse/SEC-143?redirect=false]) said:

Servlet containers often destroy sessions before an Acegi SecurityContext has been attached to them. This ends up causing a NullPointerException in JaasAuthenticationProvider.handleLogout() line 424.

java.lang.NullPointerException
    at net.sf.acegisecurity.providers.jaas.JaasAuthenticationProvider.handleLogout(JaasAuthenticationProvider.java:424)
    at net.sf.acegisecurity.providers.jaas.JaasAuthenticationProvider.onApplicationEvent(JaasAuthenticationProvider.java:413)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:45)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:224)
    at net.sf.acegisecurity.ui.session.HttpSessionEventPublisher.sessionDestroyed(HttpSessionEventPublisher.java:107)
    at com.ibm.ws.webcontainer.httpsession.SessionContext.sessionDestroyedEvent(SessionContext.java:3417)
.....

**Comment by linuxjackto1** [comment]
thanks www.movied.org
