### ISSUE TITLE
WebSecurityConfigurerAdapter.getHttp NullPointerException

### ISSUE THREAD

**Issue by talipkorkmaz** [spring-projects/spring-security#4101]
### Summary

A sample project configured with spring-boot not working when I defined a log aspect bean with @Aspect annotation.Application.properties file contains oauth2 information.
I also tried with @EnableAspectJAutoProxy and @EnableAspectJAutoProxy (proxyTargetClass = true) annotation but the error still exists.
### Actual Behavior

When application starts it writes this log after a bit while.

```
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
15:39:15.728 ERROR o.s.boot.SpringApplication org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.NullPointerException
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1128)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1023)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:751)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
    at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
    at temp.Application.main(Application.java:21)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.NullPointerException
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
    ... 19 common frames omitted
Caused by: java.lang.NullPointerException: null
    at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter.getHttp(WebSecurityConfigurerAdapter.java:174)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
    at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:201)
    at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2SsoCustomConfiguration$SsoSecurityAdapter.invoke(OAuth2SsoCustomConfiguration.java:100)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
    at temp.Application$SecurityConfiguration$$EnhancerBySpringCGLIB$$edde82d3.init(<generated>)
    at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.init(AbstractConfiguredSecurityBuilder.java:371)
    at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.doBuild(AbstractConfiguredSecurityBuilder.java:325)
    at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:41)
    at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.springSecurityFilterChain(WebSecurityConfiguration.java:104)
    at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration$$EnhancerBySpringCGLIB$$ee0e8f00.CGLIB$springSecurityFilterChain$5(<generated>)
    at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration$$EnhancerBySpringCGLIB$$ee0e8f00$$FastClassBySpringCGLIB$$e6ba2e.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
    at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration$$EnhancerBySpringCGLIB$$ee0e8f00.springSecurityFilterChain(<generated>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
    ... 20 common frames omitted
 - Application startup failed

```
### Expected Behavior

Aspect should work.
### Configuration

Application class 

```
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        new SpringApplicationBuilder(Application.class).run(args);
    }

    @LoadBalanced
    @Bean
    public OAuth2RestTemplate restTemplate(OAuth2ProtectedResourceDetails resource, OAuth2ClientContext context) {
        return new OAuth2RestTemplate(resource, context);
    }

    @Configuration
    @EnableOAuth2Sso
    protected static class SecurityConfiguration extends WebSecurityConfigurerAdapter {

        @Override
        public void configure(HttpSecurity http) throws Exception {
            http
                .logout()
                .and()
                .antMatcher("/**")
                .authorizeRequests()
                .antMatchers("/login", "/beans", "/hystrix.stream/**")
                .permitAll()
                .anyRequest()
                .authenticated()
                .and()
                .csrf()
                .disable()
                .addFilterBefore(new RequestContextFilter(), HeaderWriterFilter.class);

        }

    }

}

```

Log aspect class 

```
@Aspect
@Component
public class LogAspect {

    private static final Logger LOGGER = LoggerFactory.getLogger(LogAspect.class);

    @PostConstruct
    public void init() {
        LOGGER.info("log aspect initialized");
    }

    @Around (value = "execution (* temp.*.*(..))", argNames = "joinPoint")
    public Object aroundScreenBeansOfAydes(ProceedingJoinPoint joinPoint) throws Throwable {
        MethodSignature signature = (MethodSignature) joinPoint.getSignature();

        Object returnValue = null;
        long endTime = 0;
        long startTime = 0;

        startTime = System.nanoTime();
        returnValue = joinPoint.proceed();
        endTime = System.nanoTime();

        LOGGER.info(signature.toString() + " - duration " + (endTime - startTime) / 1000000);

        return returnValue;
    }

}
```
### Version

spring-boot-starter-parent 1.4.1.RELEASE and spring-cloud-dependencies version is Camden.RELEASE
### Sample

A sample project can be found here [https://github.com/talipkorkmaz/spring-security-gethttp-invocation](https://github.com/talipkorkmaz/spring-security-gethttp-invocation)

**Comment by rwinch** [comment]
Thanks for the sample project. This appears to be a bug in Spring Boot's auto configuration. The problem is that `SsoSecurityAdapter` is attempting to invoke a method on the `WebSecurityConfigurerAdapter` but it is invoking on the wrong object instance when AspectJ has already proxied the object.

cc @dsyer

**Comment by dsyer** [comment]
It's not a very useful aspect though, is it? So it doesn't seem like a showstopper. Custom aspects on `@Configuration` classes are hardly ever likely to be very useful, so you could change your pointcut to exclude them, I guess.

**Comment by talipkorkmaz** [comment]
@dsyer After excluding @Configuration classes from pointcut, it works.Thanks.

`@Around (value = "execution( * temp..*.*(..)) ) && !@annotation(org.springframework.context.annotation.Configuration)", argNames = "joinPoint")`

**Comment by talipkorkmaz** [comment]
I'm sorry it didnt work again.Do you offer any other pointcut expression for excluding configuration annotation?
`@Around (value = "execution (* temp.*.*(..)) && !@annotation(org.springframework.context.annotation.Configuration)", argNames = "joinPoint")`

**Comment by talipkorkmaz** [comment]
Is there any progress about this issue? Thanks in advance.

**Comment by xiaoyao9184** [comment]
The same error, when try to imitate EnableOAuth2Sso.
EnableOAuth2Sso import OAuth2SsoCustomConfiguration, 
after the creation of the proxy bean intercepted the 'init' method of the WebSecurityConfigurerAdapter implementation.

So the WebSecurityConfigurerAdapter object was delegated twice by CGLIB.
I think ReflectionUtils.invokeMethod cannot trigger CGLIB proxy callback

This code in OAuth2SsoCustomConfiguration.SsoSecurityAdapter
```java
HttpSecurity http = (HttpSecurity) ReflectionUtils.invokeMethod(method,invocation.getThis());
this.configurer.configure(http);
```
@talipkorkmaz Have you submitted this bug to spring boot?

**Comment by talipkorkmaz** [comment]
No I think this issue is enough for taking attention. Do you think that its because of spring boot?

**Comment by rwinch** [comment]
I'm closing this issue as the problem is in Spring Boot's Autoconfiguration. Please create a ticket at https://github.com/spring-projects/spring-security-oauth2-boot/
