### ISSUE TITLE
STS/Buildship error for oauth2login sample

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#4286]
### Summary

Running the oauth2login sample in STS with Buildship gives the following error:

```
java.lang.NoSuchMethodError: ch.qos.logback.core.util.Loader.getResourceOccurrenceCount(Ljava/lang/String;Ljava/lang/ClassLoader;)Ljava/util/Set;
	at ch.qos.logback.classic.util.ContextInitializer.multiplicityWarning(ContextInitializer.java:160)
	at ch.qos.logback.classic.util.ContextInitializer.statusOnResourceSearch(ContextInitializer.java:183)
	at ch.qos.logback.classic.util.ContextInitializer.getResource(ContextInitializer.java:141)
	at ch.qos.logback.classic.util.ContextInitializer.findURLOfDefaultConfigurationFile(ContextInitializer.java:130)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:148)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:156)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:274)
	at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:190)
	at org.springframework.security.samples.OAuth2LoginApplication.main(OAuth2LoginApplication.java:31)
```

**Comment by Nilkanthpatel04** [comment]
With the following setup, I have tried to run the sample.OAuth2LoginApplication and observed it running as expected (as documented in README.adoc). I have tested this for the google scenario.

Following are the details of my setup and steps i followed.
1. Spring Tool suite Version: 3.9.0.RELEASE
2. Installed buildship (Buildship Gradle integration 2.0) plug-in from the Eclipse Marketplace.
3. Cloned the project into local repository and build it from command line using "./gradlew install"
    git clone https://github.com/spring-projects/spring-security.git
    
    and, Imported it in STS using,
    File -> Import -> Gradle -> Existing Gradle Project

4. For Google Identity Platform, setup a OAuth 2.0.
   - Created oAuth Client ID for "web application" type and added 
      authorized redirect URI to "http://localhost:8080/oauth2/authorize/code/google"
5. Updated the "application.yml" with the "client-id" and "client-secret" created in step-4.

6.  Screenshot demonstrating the console output for the sample run.
    
7. Browsing http://localhost:8080

8. clicking on google, prompts the google sign-in page. After submitting the valid google credentials it show the,

9. clicking on logout prompts the following logout page but subsequent request to http://localhost:8080 shows directly the logged-in page and does not ask for google login. Is this "logout" only a application specific logout and not the global one.?

As I am getting started contributing to the spring-security project, kindly correct me if i am misunderstanding anything.

**Comment by Nilkanthpatel04** [comment]
Adding the screen-shots for the better understanding.
6. Screenshot demonstrating the console output for the sample run.
![oauth2login-sts-buildship-sample-run](https://user-images.githubusercontent.com/7866426/29870976-b4f0ac1c-8da7-11e7-853b-3f195de7eb5d.png)

7. Browsing http://localhost:8080
![screen-1](https://user-images.githubusercontent.com/7866426/29871002-d10ab244-8da7-11e7-948a-948cc379af52.png)

8. clicking on google, prompts the google sign-in page. After submitting the valid google credentials it show the,
![screen-2](https://user-images.githubusercontent.com/7866426/29871038-f436d72a-8da7-11e7-85f0-6ce275602922.png)

9. clicking on logout prompts the following logout page but subsequent request to http://localhost:8080 shows directly the logged-in page as captured in step-8, without asking for the google creds.
![screen-3](https://user-images.githubusercontent.com/7866426/29871078-1f675cb2-8da8-11e7-97f9-f887242440e6.png)

**Comment by jgrandja** [comment]
@Nilkanthpatel04 Yes, the logout is for the local application only. Since you have authenticated with Google and have established a session with your browser, you will not be prompted for your Google credentials again. We may introduce a feature that does a back-channel logout with the provider in the future.

Thanks for testing with STS/Buildship and confirmed that it's working. It was a while back when we logged this issue and seems like it's been resolved. I will leave the issue open for now and try it in my environment as well.
Thanks.

**Comment by jgrandja** [comment]
I just tried running the oauth2Login sample using the Buildship Gradle 2.0 plug-in and had no issues.
