### ISSUE TITLE
SEC-168: ConcurrentSessionFilter breaks authenticate with: Authentication.getDetails() required

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#429]
["Veit Guna":https://jira.spring.io/secure/ViewProfile.jspa?name=vguna](Migrated from ["SEC-168":https://jira.spring.io/browse/SEC-168?redirect=false]) said:

Acegi works fine for me in my environment. 

Now i wanted to avoid concurrent logins and followed the steps described at: http://acegisecurity.org/docbook/acegi.html#security-authentication-concurrent-login

Now, when I try to login with the same code that worked before, I get an exception:

Caused by: java.lang.IllegalArgumentException: Authentication.getDetails() required
    at org.springframework.util.Assert.notNull(Assert.java:90)
    at org.acegisecurity.concurrent.SessionRegistryUtils.obtainSessionIdFromAuthentication(SessionRegistryUtils.java:48)
    at org.acegisecurity.concurrent.ConcurrentSessionControllerImpl.checkAuthenticationAllowed(ConcurrentSessionControllerImpl.java:100)
    at org.acegisecurity.providers.ProviderManager.doAuthentication(ProviderManager.java:209)
    at org.acegisecurity.AbstractAuthenticationManager.authenticate(AbstractAuthenticationManager.java:49)

Here is the code snippet:

```
    Authentication lAuthReq = new UsernamePasswordAuthenticationToken(pUsername, pPassword);

    Authentication lAuth = null;

    lAuth = getAuthenticationManager().authenticate(lAuthReq);
```

Without the concurrent session filter it works perfectly...

**Comment by linuxjackto1** [comment]
thanks www.movied.org
