### ISSUE TITLE
SEC-181: Acegifier XML parser issues

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#437]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-181":https://jira.spring.io/browse/SEC-181?redirect=false]) said:

Executing WebXmlConverter tests causes an exception. I have disabled the test as Acegifier is not a core part of the 1.0.0 RC2 release but it was blocking it. The exception is:

java.lang.NoClassDefFoundError: org/jaxen/JaxenException
    at org.dom4j.DocumentFactory.createXPath(DocumentFactory.java:230)
    at org.dom4j.tree.AbstractNode.createXPath(AbstractNode.java:207)
    at org.dom4j.tree.AbstractNode.selectSingleNode(AbstractNode.java:183)
    at acegifier.WebXmlConverter.validateWebXml(WebXmlConverter.java:110)
    at acegifier.WebXmlConverter.setInput(WebXmlConverter.java:103)
    at acegifier.WebXmlConverter.setInput(WebXmlConverter.java:98)
    at acegifier.WebXmlConverterTests.testFileConversion(WebXmlConverterTests.java:51)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at junit.framework.TestCase.runTest(TestCase.java:154)
    at junit.framework.TestCase.runBare(TestCase.java:127)
    at junit.framework.TestResult$1.protect(TestResult.java:106)
    at junit.framework.TestResult.runProtected(TestResult.java:124)
    at junit.framework.TestResult.run(TestResult.java:109)
    at junit.framework.TestCase.run(TestCase.java:118)
    at junit.framework.TestSuite.runTest(TestSuite.java:208)
    at junit.framework.TestSuite.run(TestSuite.java:203)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:478)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:344)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)

**Comment by linuxjackto1** [comment]
thanks www.movied.org
