### ISSUE TITLE
ConcurrentModificationException in DelegatingApplicationListener

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4416]
### Summary

Fix https://jira.spring.io/browse/SPR-15694

Setup:
Spring version :4.3.6
Spring security: 4.2.1
Spring Session: 1.3.1
Spring data redis : 1.7.2

I have a clustered MVC Webapp with external Redis for Session Management 

I get this Exception all the time:

```
java.util.ConcurrentModificationException
     at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
     at java.util.ArrayList$Itr.next(ArrayList.java:851)
     at org.springframework.security.context.DelegatingApplicationListener.onApplicationEvent(DelegatingApplicationListener.java:41)
     at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
     at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
     at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:382)
     at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:336)
     at org.springframework.security.web.session.HttpSessionEventPublisher.sessionDestroyed(HttpSessionEventPublisher.java:91)
     at org.springframework.session.web.http.SessionEventHttpSessionListenerAdapter.onApplicationEvent(SessionEventHttpSessionListenerAdapter.java:67)
     at org.springframework.session.web.http.SessionEventHttpSessionListenerAdapter.onApplicationEvent(SessionEventHttpSessionListenerAdapter.java:41)
     at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
     at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
     at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:382)
     at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:336)
     at org.springframework.session.data.redis.RedisOperationsSessionRepository.publishEvent(RedisOperationsSessionRepository.java:576)
     at org.springframework.session.data.redis.RedisOperationsSessionRepository.handleExpired(RedisOperationsSessionRepository.java:570)
     at org.springframework.session.data.redis.RedisOperationsSessionRepository.onMessage(RedisOperationsSessionRepository.java:531)
     at org.springframework.data.redis.listener.RedisMessageListenerContainer.executeListener(RedisMessageListenerContainer.java:249)
     at org.springframework.data.redis.listener.RedisMessageListenerContainer.processMessage(RedisMessageListenerContainer.java:239)
     at org.springframework.data.redis.listener.RedisMessageListenerContainer$1.run(RedisMessageListenerContainer.java:967)
     at java.lang.Thread.run(Thread.java:745)
```

Seems like Redis is trying to send events During the webapp restart and this happens during the time My own SmartListener is registering itself against DelegatingApplicationListener

My Listener is registering agains tthe DelegatingApplicationListener using constructor autowiring

```java
    public xxxx(ObjectMapper mapper,SessionRepository<? extends ExpiringSession> sessionRepository,DelegatingApplicationListener delegatingApplicationListener) {
        this.mapper = mapper;
        this.sessionRepository = sessionRepository;
        delegatingApplicationListener.addListener(this);

    }
```

Seems like the DelegatingApplicationListener should handle this

**Comment by rwinch** [comment]
We should be able to use `CopyOnWriteArrayList` which would be ideal since we don't expect a lot of writes and do expect a lot of reads
