### ISSUE TITLE
Spring security 5 "Bad credentials" exception not shown with errorDetails

### ISSUE THREAD

**Issue by fred01** [spring-projects/spring-security#4467]
### Summary
I'm just switch from Spring Boot 1.5.4 to 2.0.0.BUILD-SNAPSHOT. Most functionality migrate seamless, but i meet strange behavior of BadCredentialsException handling. In Spring 4 it was show as all other exceptions, like

```
{
    "error": "Unauthorized",
    "message": "Bad credentials",
    "path": "/v1/admin/users",
    "status": 401,
    "timestamp": "2017-07-25T10:53:13+0000"
}

```

But now just empty response with code 401 produced. All other spring security exceptions like "Forbidden" shown as expected in JSON. 

### Actual Behavior

Just 

`HTTP/1.1 401`

on BadCredentialsException
### Expected Behavior
Full JSON body

```
{
    "error": "Unauthorized",
    "message": "Bad credentials",
    "path": "/v1/admin/users",
    "status": 401,
    "timestamp": "2017-07-25T10:53:13+0000"
}

```
on BadCredentialsException
### Configuration

Only default spring security properties, no additional properties set

### Version

Spring Boot 2.0.0 SNAPSHOT, Spring Framework 5.0.0.M3

### Sample

Sorry, part of production project

**Comment by fred01** [comment]
Solved by myself. In Spring Security 5.0 necessary to permit all access to /error endpoint, for all http methods

**Comment by fred01** [comment]
Hi!
Actually it's Spring Boot 2 related issue, so i close it here.
I meet this problem twice.
First time i solved it by adding 
                .antMatchers("/error").permitAll()
Sometime later new Spring Boot 2 milestone broke it again. and second time it was broken completely. I make workaround then, but it was worst solution even i did. I'd intercept Spring Boot error controller and replace error in response.

**Comment by jzheaux** [comment]
Actually, this was a proactive decision in the 2.x release of Boot, though I think we should do a better job of explaining the rationale (for which I've just logged [a ticket to the Boot team](https://github.com/spring-projects/spring-boot/issues/14474)).

The ticket also includes some of the reasoning, too, but I'll briefly summarize here:

- Spring Security secures all endpoints by default. (You can see this is the case by looking at the default implementation of `configure` in `WebSecurityConfigurerAdapter`). It was surprising (and less secure) that somehow `/error` wasn't included in the set of "all endpoints".
- And the way that Spring Boot excluded `/error` from Spring Security was actually to bypass the filter chain altogether, meaning that secure headers, https redirect, and other important security protections were not invoked.

So, actually, yes, if you want the Spring Boot `/error` page to be permitted, then it is more secure for you to declaratively say so. This makes it clear in your app what security allowances you are making.

**Comment by bhartishradha** [comment]
HI 

I recently did upgrade of spring boot 2.1.7 and suddently I was not getting any error message ..I found some idea with this issue
so to fix this ..i have given this
antMatchers("/error").permitAll()
but now I m getting the error message but message are coming different
so previously before upgrade when i was putting wrong username/pwd ...the response was
{
"timestamp": 1571049553776,
"status": 401,
"error": "Unauthorized",
"message": "Authentication Failed: {\"errorCode\":\"52e\",\"adminMail\":\"System Administrator\",\"role\":[]}",
"path": "/login/auth"
}
and now after upgrade,this is the response
{
"timestamp": "2019-10-14T10:40:37.651+0000",
"status": 401,
"error": "Unauthorized",
"message": "Unauthorized",
"path": "/login/auth"
}

Let me know if somebody can help me for this

**Comment by tjmjansen** [comment]
> HI
> 
> I recently did upgrade of spring boot 2.1.7 and suddently I was not getting any error message ..I found some idea with this issue
> so to fix this ..i have given this
> antMatchers("/error").permitAll()
> but now I m getting the error message but message are coming different
> so previously before upgrade when i was putting wrong username/pwd ...the response was
> {
> "timestamp": 1571049553776,
> "status": 401,
> "error": "Unauthorized",
> "message": "Authentication Failed: {"errorCode":"52e","adminMail":"System Administrator","role":[]}",
> "path": "/login/auth"
> }
> and now after upgrade,this is the response
> {
> "timestamp": "2019-10-14T10:40:37.651+0000",
> "status": 401,
> "error": "Unauthorized",
> "message": "Unauthorized",
> "path": "/login/auth"
> }
> 
> Let me know if somebody can help me for this

I have the same issue, did you find a solution?

**Comment by bhartishradha** [comment]
> > HI
> > I recently did upgrade of spring boot 2.1.7 and suddently I was not getting any error message ..I found some idea with this issue
> > so to fix this ..i have given this
> > antMatchers("/error").permitAll()
> > but now I m getting the error message but message are coming different
> > so previously before upgrade when i was putting wrong username/pwd ...the response was
> > {
> > "timestamp": 1571049553776,
> > "status": 401,
> > "error": "Unauthorized",
> > "message": "Authentication Failed: {"errorCode":"52e","adminMail":"System Administrator","role":[]}",
> > "path": "/login/auth"
> > }
> > and now after upgrade,this is the response
> > {
> > "timestamp": "2019-10-14T10:40:37.651+0000",
> > "status": 401,
> > "error": "Unauthorized",
> > "message": "Unauthorized",
> > "path": "/login/auth"
> > }
> > Let me know if somebody can help me for this
> 
> I have the same issue, did you find a solution?

No ..
I am still trying to find the solution

**Comment by bhartishradha** [comment]
> > HI
> > I recently did upgrade of spring boot 2.1.7 and suddently I was not getting any error message ..I found some idea with this issue
> > so to fix this ..i have given this
> > antMatchers("/error").permitAll()
> > but now I m getting the error message but message are coming different
> > so previously before upgrade when i was putting wrong username/pwd ...the response was
> > {
> > "timestamp": 1571049553776,
> > "status": 401,
> > "error": "Unauthorized",
> > "message": "Authentication Failed: {"errorCode":"52e","adminMail":"System Administrator","role":[]}",
> > "path": "/login/auth"
> > }
> > and now after upgrade,this is the response
> > {
> > "timestamp": "2019-10-14T10:40:37.651+0000",
> > "status": 401,
> > "error": "Unauthorized",
> > "message": "Unauthorized",
> > "path": "/login/auth"
> > }
> > Let me know if somebody can help me for this
> 
> I have the same issue, did you find a solution?

HI 
I wrote a customefailure handler and with that it worked

**Comment by tjmjansen** [comment]
How did you do that? I tried but exceptions are still coming out in the same manner

**Comment by rubensa** [comment]
I'm facing this problem too.
The most unexpected behavior is that **if user credentials are not included** at all then a **401 Unauthorized** response that **includes JSON response** (like with any exception) is returned, but **if wrong credentials are provided** then a **401 Unauthorized** is returned but **without any JSON**.
I think this is not very "consistent" behavior.

**Comment by bhartishradha** [comment]
no it wokred after applying some code.
let me forward that code

**Comment by bhartishradha** [comment]
i created an object of UsernamePasswordAuthenticationFilter and set setAuthenticationFailureHandler
like below
 UsernamePasswordAuthenticationFilter authFilter = new UsernamePasswordAuthenticationFilter();

        AuthenticationProvider provider = initAuthenticationProvider();
        authFilter.setAuthenticationManager(new ProviderManager(Arrays.asList(provider)));

        // set redirect on success and submit form params
        SavedRequestAwareAuthenticationSuccessHandler authOkHandler =
            new SavedRequestAwareAuthenticationSuccessHandler();
        authOkHandler.setDefaultTargetUrl("/portal/index.html");
        authFilter.setAuthenticationSuccessHandler(authOkHandler);
        authFilter.setFilterProcessesUrl("/login/auth");
        authFilter.setUsernameParameter("username");
        authFilter.setPasswordParameter("password");
        authFilter.setAuthenticationFailureHandler(customAuthenticationFailureHandler());

the create a bean 
 @Bean
    public AuthenticationFailureHandler customAuthenticationFailureHandler() {
        return new CustomAuthenticationFailureHandler();
    }

and here is the implementation of CustomAuthenticationFailureHandler(i wrote according to the logic of my application 

public class CustomAuthenticationFailureHandler implements AuthenticationFailureHandler{
    private ObjectMapper objectMapper = new ObjectMapper();
    private static final Logger log = LogManager.getLogger(CustomAuthenticationFailureHandler.class);
    public CustomAuthenticationFailureHandler() {
        log.info("CustomAuthenticationFailureHandler :started");
    }
    @Override
    public void onAuthenticationFailure(HttpServletRequest request, HttpServletResponse response,
                                        AuthenticationException exception)
        throws IOException, ServletException {
       
        log.info("CustomAuthenticationFailureHandler :Method >>started");
        response.setStatus(HttpStatus.UNAUTHORIZED.value());
        Map<String, Object> data = new LinkedHashMap<String, Object>();
        data.put(
          "timestamp", 
          Calendar.getInstance().getTime());
        
        data.put(
                 "status", 
                 HttpStatus.UNAUTHORIZED.value());
       
        data.put(
                 "error", 
                 HttpStatus.UNAUTHORIZED.getReasonPhrase());
        data.put(
                 "message", "Authentication Failed: "+
                 exception.getMessage());
        data.put("path", request.getRequestURI());
 
        response.getOutputStream()
          .println(objectMapper.writeValueAsString(data));
        
    }

**Comment by rubensa** [comment]
@bhartishradha thanks for your code but I was talking about the inconsistency in the "default" implementation (If you override the behavior you can do "almost" anything you want).
I opened an issue here: https://github.com/spring-projects/spring-boot/issues/26356

**Comment by Sanskar49** [comment]
Hey @bhartishradha I too am facing the same issue or could be a little different.  I am getting a "org.springframework.security.authentication.BadCredentialsException: Bad credentials" when I hit my API through Postman(Post req) and eventhough my creds are correct, it still is giving me this error? Did you have the same problem? I saw your code.. The part where you created an object of UsernamePasswordAuthenticationFilter and then did all the authFilter.setAuthenticationSuccessHandler(authOkHandler);
authFilter.setFilterProcessesUrl("/login/auth");                                                                                                                                     I wanted to ask where you did this? In your controller method or where speceficly? I am getting this error since 2 days.. If anyone could help that'd be great.

**Comment by brytkhalifa** [comment]
> 

@Sanskar49  Where you able to solve this problem?

**Comment by sebasira** [comment]
I'm having the same problem!

I'm getting this:
{
"timestamp": "2019-10-14T10:40:37.651+0000",
"status": 401,
"error": "Unauthorized",
"message": "Unauthorized",
"path": "/login/auth"
}

instead of the custom message I was having before. Could anyone help here?

**Comment by sebasira** [comment]
I resolved by setting the `AuthenticationFailureHandler` in my `JWTAuthenticationFilter` that extends `UsernamePasswordAuthenticationFilter`

The answer from @bhartishradha give me a clue

**Comment by m-usman-24** [comment]
Writing for you all and also for my help, I am using spring security 6+ and spring boot 3.1.1 solved this issue for simple form login like this 

`
@AllArgsConstructor
@EqualsAndHashCode
@Configuration
@EnableWebSecurity
public class SecurityConfig {
	
	private final UserDetailsService userDetailsService;
	private final CustomAuthenticationFailureHandler failureHandler;
	private final PasswordEncoder passwordEncoder;
	
	@Bean
	public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
		
		http
			.authorizeHttpRequests(configurer ->
				configurer
// these requestMatchers here are for static resources as /static is allowed but the sub paths of static folder are not allowed by default
					.requestMatchers("/css/**")
					.permitAll()
					.requestMatchers("/javascript/**")
					.permitAll()
// these are now controller endpoints
					.requestMatchers("/login/**")
					.permitAll()
					.requestMatchers("/signup/**")
					.permitAll()
					.requestMatchers("/forgot/**")
					.permitAll()
					.anyRequest()
					.authenticated()
			)

// here is the form login I am generating views using @Controller annotation in my controllers here 

			.formLogin(configurer ->
				configurer
					.loginPage("/login")
					.loginProcessingUrl("/login")

// this is the custom faliure handler

					.failureHandler(failureHandler)
					.defaultSuccessUrl("/notes", true)
			)
			.authenticationProvider(daoAuthenticationProvider());
			
		return http.build();
	}
	
	@Bean
	public DaoAuthenticationProvider daoAuthenticationProvider() {
		
		DaoAuthenticationProvider provider = new DaoAuthenticationProvider();
		provider.setUserDetailsService(userDetailsService);
		provider.setPasswordEncoder(passwordEncoder);
		
		return provider;
	}
	
}

`

Here is the implementation of custom failure handler

`

@Component
public class CustomAuthenticationFailureHandler extends SimpleUrlAuthenticationFailureHandler {
	@Override
	public void onAuthenticationFailure(HttpServletRequest request,
	                                    HttpServletResponse response,
	                                    AuthenticationException exception)
		throws IOException, ServletException {
		
		String exceptionName = exception.getClass().getSimpleName();
		StringBuilder failureUrl = new StringBuilder("/login?error=");
		
		for (int i = 0 ; i < exceptionName.length() ; i++) {
			char ch = exceptionName.charAt(i);
			if (Character.isUpperCase(ch)) {
				failureUrl.append(Character.toLowerCase(ch));
			}
		}
		
		getRedirectStrategy().sendRedirect(request, response, failureUrl.toString());
	}
}

`

now from here user is redirected back to login page with added **request param** after that I am using thymeleaf

`



<div data-th-class="${#strings.equals(param.error, 'bce')} ? alertNegative"
             data-th-if="${#strings.equals(param.error, 'bce')}"><p>Bad Credentials</p></div>

        <div data-th-class="${#strings.equals(param.error, 'aee')} ? alertNegative"
             data-th-if="${#strings.equals(param.error, 'aee')}"><p>Your Account is Expired</p></div>

        <div data-th-class="${#strings.equals(param.error, 'le')} ? alertNegative"
             data-th-if="${#strings.equals(param.error, 'le')}"><p>Your Account is disable, verify your email to
          enable it</p></div>

        <div data-th-class="${#strings.equals(param.error, 'de')} ? alertNegative"
             data-th-if="${#strings.equals(param.error, 'de')}"><p>Your Account is Disabled</p></div>

        <div data-th-class="${#strings.equals(param.error, 'cee')} ? alertNegative"
             data-th-if="${#strings.equals(param.error, 'cee')}"><p>Your Credentials are Expired</p></div>

        <div data-th-class="${errorMessage != null} ? alertNegative">
          <p data-th-text="${errorMessage} ?: _"></p>
        </div>


`

** What I did above was to generate views and for form login to handle exceptions for my custom implementation of login page **

like this attached image
![Screenshot (109)](https://github.com/spring-projects/spring-security/assets/105865001/da4ad0c7-38dd-49d5-a0fc-73785a934cc3)


Now where I am stuck is this, I am trying to do the same for my rest api here I am using http basic auth

here is my security config


`

@RequiredArgsConstructor
@Configuration
@EnableWebSecurity
public class SecurityConfig {
	
	private final AuthenticationProvider authenticationProvider;
	private final CustomAuthenticationEntryPoint entryPoint;
	
	@Bean
	public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
		
		return http
			.authorizeHttpRequests(customizer ->
				customizer

//if you put this /error requestMatcher here the commence method of BasicAuthenticationEntryPoint will not run IDK why

					//.requestMatchers("/error")
					.permitAll()
					.requestMatchers("/letschat/auth/test", "/letschat/auth/update")
					.authenticated()
					.requestMatchers("/letschat/auth**")
					.permitAll()
					.anyRequest()
					.authenticated()
			)
			.csrf(AbstractHttpConfigurer::disable)
			.authenticationProvider(authenticationProvider)

// here is the http Basic auth

			.httpBasic(Customizer.withDefaults())

// I tried this exceptionHandling to handle it but failed, first lets see what is the implementation I did for this custom authentication entry point below
			.exceptionHandling(customizer ->
				customizer.authenticationEntryPoint(entryPoint)
			)
			.build();
		
	}
}

`

**if you use this .requestMatchers("/error") you get this response
{
"timestamp": "2019-10-14T10:40:37.651+0000",
"status": 401,
"error": "Unauthorized",
"message": "Unauthorized",
"path": "/login/auth"
}

if you don't you simply get 401 Unauthorized** 

here is the implementation for authenticationEntryPoint

`

@Component
public class CustomAuthenticationEntryPoint extends BasicAuthenticationEntryPoint {
	@Override
	public void commence(HttpServletRequest request,
	                     HttpServletResponse response,
	                     AuthenticationException authException)
		throws IOException {
		
		if (authException instanceof BadCredentialsException) {
			response.sendError(HttpServletResponse.SC_UNAUTHORIZED, "Bad Credentials");
			
		} else if (authException instanceof LockedException) {
			response.sendError(HttpServletResponse.SC_UNAUTHORIZED, "Account Locked, Unverified Email");
			
		} else if (authException instanceof DisabledException) {
			response.sendError(HttpServletResponse.SC_UNAUTHORIZED, "Account Disabled, Unverified Email");
			
		} else {
			response.sendError(HttpServletResponse.SC_UNAUTHORIZED, "Unauthorized, Unknown Reasons");
		}
	}
	
	@Override
	public void afterPropertiesSet() {
		setRealmName("Secure Access Point");
		super.afterPropertiesSet();
	}
}

`

but the exception that lands here when this commence method is called is not these mentioned in the conditions but to my surprise is 

** org.springframework.security.authentication.InsufficientAuthenticationException: Full authentication is required to access this resource **

the debug logs says 


`

org.springframework.security.authentication.BadCredentialsException: Bad credentials
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:141) ~[spring-security-core-6.1.2.jar:6.1.2]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182) ~[spring-security-core-6.1.2.jar:6.1.2]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:201) ~[spring-security-core-6.1.2.jar:6.1.2]
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:174) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) ~[spring-web-6.0.11.jar:6.0.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar:6.0.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar:6.0.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.11.jar:6.0.11]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar:6.0.11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
	at java.base/java.lang.Thread.run(Thread.java:1623) ~[na:na]


`

AbstractUserDetailsAuthenticationProvider this class you can see in the logs above handles these checks and throws these exceptions 

here is the code from the source of this class

`

private class DefaultPreAuthenticationChecks implements UserDetailsChecker {
        private DefaultPreAuthenticationChecks() {
        }

        public void check(UserDetails user) {
            if (!user.isAccountNonLocked()) {
                AbstractUserDetailsAuthenticationProvider.this.logger.debug("Failed to authenticate since user account is locked");
                throw new LockedException(AbstractUserDetailsAuthenticationProvider.this.messages.getMessage("AbstractUserDetailsAuthenticationProvider.locked", "User account is locked"));
            } else if (!user.isEnabled()) {
                AbstractUserDetailsAuthenticationProvider.this.logger.debug("Failed to authenticate since user account is disabled");
                throw new DisabledException(AbstractUserDetailsAuthenticationProvider.this.messages.getMessage("AbstractUserDetailsAuthenticationProvider.disabled", "User is disabled"));
            } else if (!user.isAccountNonExpired()) {
                AbstractUserDetailsAuthenticationProvider.this.logger.debug("Failed to authenticate since user account has expired");
                throw new AccountExpiredException(AbstractUserDetailsAuthenticationProvider.this.messages.getMessage("AbstractUserDetailsAuthenticationProvider.expired", "User account has expired"));
            }
        }
    }

    private class DefaultPostAuthenticationChecks implements UserDetailsChecker {
        private DefaultPostAuthenticationChecks() {
        }

        public void check(UserDetails user) {
            if (!user.isCredentialsNonExpired()) {
                AbstractUserDetailsAuthenticationProvider.this.logger.debug("Failed to authenticate since user account credentials have expired");
                throw new CredentialsExpiredException(AbstractUserDetailsAuthenticationProvider.this.messages.getMessage("AbstractUserDetailsAuthenticationProvider.credentialsExpired", "User credentials have expired"));
            }
        }
    }

`

now as you can see the flow of exception as it passes in debug logs I tried to intercept it at here, org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:174) ~[spring-security-web-6.1.2.jar:6.1.2]

by using the custom basic authentication entry point as it calls the commence method in here

code snippet for this method BasicAuthenticationFilter.doFilterInternal

`this.authenticationEntryPoint.commence(request, response, var8);`

but as I discussed above the exception that lands here is different from what I want to intercept 

**Now my question is, is there a way to intercept these exceptions like bad credentials, account locked etc  before this BasicAuthenticationFilter.doFilterInternal, what I want to do is intercept the actual exceptions being thrown to send custom messages**

If the account is locked the reason is your email is not verified not just 401 

is there a way please help me
