### ISSUE TITLE
Spring security 4.2.X documentation has bug under the title "Form and Basic Login Options"

### ISSUE THREAD

**Issue by Divine1** [spring-projects/spring-security#4470]
### Summary

i went through the [spring documentation](http://docs.spring.io/spring-security/site/docs/4.2.x/reference/htmlsingle/#ns-form-and-basic). 
i think there is a bug in the example provided in this part. i referred [this documentation](https://docs.spring.io/spring-security/site/docs/3.0.x/reference/anonymous.html)  to fix this bug.

The value `IS_AUTHENTICATED_ANONYMOUSLY` for `access` attribute doesn't work. Exception is thrown when we use this value. You can see the exception in this post below.

The valid value for `access `attribute seems to be `hasRole('ROLE_ANONYMOUS')`
The ready-to-run project prototype setup for testing this scenario is in [my git repository](https://github.com/Divine1/Spring-web/tree/master/springsecurityTest1/setup-security-xml)

**My analysis is below**

### Actual code [in documentation](http://docs.spring.io/spring-security/site/docs/4.2.x/reference/htmlsingle/#ns-form-and-basic)
```
<http>
        <intercept-url pattern="/login.jsp*" access="IS_AUTHENTICATED_ANONYMOUSLY"/>
        <intercept-url pattern="/**" access="ROLE_USER" />
        <form-login login-page='/login.jsp'/>
</http>
```
**This resulted in Exception**
```
Jul 26, 2017 3:23:48 PM org.springframework.security.config.http.DefaultFilterChainValidator checkLoginPageIsntProtected
INFO: Unable to check access to the login page to determine if anonymous access is allowed. This might be an error, but can happen under normal circumstances.
java.lang.IllegalArgumentException: Failed to evaluate expression 'IS_AUTHENTICATED_ANONYMOUSLY'
	at org.springframework.security.access.expression.ExpressionUtils.evaluateAsBoolean(ExpressionUtils.java:30)
	at org.springframework.security.web.access.expression.WebExpressionVoter.vote(WebExpressionVoter.java:52)
	at org.springframework.security.web.access.expression.WebExpressionVoter.vote(WebExpressionVoter.java:33)
	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:63)
	at org.springframework.security.config.http.DefaultFilterChainValidator.checkLoginPageIsntProtected(DefaultFilterChainValidator.java:206)
	at org.springframework.security.config.http.DefaultFilterChainValidator.validate(DefaultFilterChainValidator.java:51)
	at org.springframework.security.web.FilterChainProxy.afterPropertiesSet(FilterChainProxy.java:168)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1227)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1140)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1027)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5038)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5348)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1008E:(pos 0): Property or field 'IS_AUTHENTICATED_ANONYMOUSLY' cannot be found on object of type 'org.springframework.security.web.access.expression.WebSecurityExpressionRoot' - maybe not public?
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:224)
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:94)
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:81)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:131)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:299)
	at org.springframework.security.access.expression.ExpressionUtils.evaluateAsBoolean(ExpressionUtils.java:26)
	... 36 more
```

### Actual Code: modified **1**
```
<http>
	<intercept-url pattern="/login" access="hasRole('IS_AUTHENTICATED_ANONYMOUSLY')" />
	<intercept-url pattern="/**" access="hasRole('ROLE_USER')" />
	<form-login login-page="/login" />
</http>
```
**The apache tomcat server started successfully but we get below warning**
`WARNING: Anonymous access to the login page doesn't appear to be enabled. This is almost certainly an error. Please check your configuration allows unauthenticated access to the configured login page. (Simulated access was rejected: org.springframework.security.access.AccessDeniedException: Access is denied)`

### Valid Code
```
<http>
        <intercept-url pattern="/login" access="hasRole('ROLE_ANONYMOUS')" /> 
	<intercept-url pattern="/**" access="hasRole('ROLE_USER')" />
	<form-login login-page="/login" />
</http>
```

**Only this code gave me a valid result.**

Please verify my analysis and update [the documentation](http://docs.spring.io/spring-security/site/docs/4.2.x/reference/htmlsingle/#ns-form-and-basic) with valid code if my analysis is right

**Comment by rwinch** [comment]
Thanks for the detailed report! You are right this is an issue from when we changed the default behavior to use expressions is Spring Security 4.0.

The easy fix is to add `use-expressions="false"` to the sample that you are linking to. 

A cleaner solution is to use `permitAll` expression rather than `hasRole('ROLE_ANONYMOUS')` as this the translation for expression based access control. We should also update all the samples to remove  `use-expressions="false"` to give a more consistent experience.


Would you be interested in submitting a PR to resolve this?

**Comment by Divine1** [comment]
**"Would you be interested in submitting a PR to resolve this?"** Yes, iam interested.

Also, i have another concern which isn't related to this issue raised here, but the concern is related to the spring documentation. 

i just started reading the documentation for spring security namespace configuration. 
i'm facing difficulties while implementing  custom authentication provider, could you let me know the link to the article that describes how to implement custom authentication provider?

 i have uploaded a screenshot of [the documentation that summarizes this](http://docs.spring.io/spring-security/site/docs/4.2.x/reference/htmlsingle/#ns-config), but i'm looking for spring documentation details on how to implement the custom authentication provider. i'm not sure whether i missed reading it in this article itself. kindly help me out.

![untitled](https://user-images.githubusercontent.com/10482177/28703253-73cb35ae-7380-11e7-9927-5663c595621f.png)
