### ISSUE TITLE
Redirect URI matching doesn't work properly in case of HTTPS 

### ISSUE THREAD

**Issue by making** [spring-projects/spring-security#4625]
### Summary

I'm using Spring Security 5.0.0.M5 with Spring Boot 2.0.0.M5.
I tried OAuth2 Client Login with GitHub and worked well in local environment.
But redirect URI matching failed in Cloud Foundry environment using HTTPS.

here is stacktrace.

```
   2017-10-13T03:49:27.39+0900 [APP/PROC/WEB/0] OUT 2017-10-12 18:49:27.395 DEBUG 14 --- [nio-8080-exec-5] o.s.s.web.DefaultRedirectStrategy        : Redirecting to 'https://github.com/login/oauth/authorize?response_type=code&redirect_uri=https://demodemo-admin.cfapps.pez.pivotal.io:443/oauth2/authorize/code/github&client_id=a4091c323af504f07a57&scope=user:email&state=adO2Mch0aPMSA6vxWSlYSB464avdBYh36sDU3rGD048%3D'
   2017-10-13T03:49:27.39+0900 [APP/PROC/WEB/0] OUT 2017-10-12 18:49:27.395 DEBUG 14 --- [nio-8080-exec-5] w.c.HttpSessionSecurityContextRepository : SecurityContext is empty or contents are anonymous - context will not be stored in HttpSession.
   2017-10-13T03:49:27.39+0900 [APP/PROC/WEB/0] OUT 2017-10-12 18:49:27.395 DEBUG 14 --- [nio-8080-exec-5] s.s.w.c.SecurityContextPersistenceFilter : SecurityContextHolder now cleared, as request processing completed
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 2017-10-12 18:49:28.499 DEBUG 14 --- [nio-8080-exec-6] w.c.HttpSessionSecurityContextRepository : HttpSession returned null object for SPRING_SECURITY_CONTEXT
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 2017-10-12 18:49:28.499 DEBUG 14 --- [nio-8080-exec-6] w.c.HttpSessionSecurityContextRepository : No SecurityContext was available from the HttpSession: org.apache.catalina.session.StandardSessionFacade@55150eba. A new one will be created.
   2017-10-13T03:49:28.86+0900 [RTR/1] OUT demodemo-admin.cfapps.pez.pivotal.io - [2017-10-12T18:49:28.853+0000] "GET /login?error HTTP/1.1" 200 0 304 "https://demodemo-admin.cfapps.pez.pivotal.io/login?error" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "192.168.8.1:63538" "192.168.8.207:61001" x_forwarded_for:"10.200.21.24" x_forwarded_proto:"https" vcap_request_id:"35037e64-47d6-4615-6acc-dd503ce908a1" response_time:0.006952983 app_id:"e6a2a747-70aa-4ea7-af4b-23da5eb82272" app_index:"0" x_b3_traceid:"673b761cf298cae0" x_b3_spanid:"673b761cf298cae0" x_b3_parentspanid:"-"
   2017-10-13T03:49:28.86+0900 [RTR/1] OUT 

   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 2017-10-12 18:49:28.500 DEBUG 14 --- [nio-8080-exec-6] .w.AuthorizationCodeAuthenticationFilter : Request is to process authentication
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 2017-10-12 18:49:28.501 DEBUG 14 --- [nio-8080-exec-6] o.s.s.authentication.ProviderManager     : Authentication attempt using org.springframework.security.oauth2.client.authentication.AuthorizationCodeAuthenticationProvider
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 2017-10-12 18:49:28.502 DEBUG 14 --- [nio-8080-exec-6] .w.AuthorizationCodeAuthenticationFilter : Authentication request failed: org.springframework.security.oauth2.client.authentication.OAuth2AuthenticationException: [invalid_redirect_uri_parameter] 
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT org.springframework.security.oauth2.client.authentication.OAuth2AuthenticationException: [invalid_redirect_uri_parameter] 
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.oauth2.client.authentication.AuthorizationCodeAuthenticationProvider.authenticate(AuthorizationCodeAuthenticationProvider.java:87) ~[spring-security-oauth2-client-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:174) ~[spring-security-core-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.oauth2.client.web.AuthorizationCodeAuthenticationFilter.attemptAuthentication(AuthorizationCodeAuthenticationFilter.java:138) ~[spring-security-oauth2-client-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212) ~[spring-security-web-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.oauth2.client.web.AuthorizationCodeRequestRedirectFilter.doFilterInternal(AuthorizationCodeRequestRedirectFilter.java:111) [spring-security-oauth2-client-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) [spring-security-web-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100) [spring-security-web-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64) [spring-security-web-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) [spring-security-web-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) [spring-security-web-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214) [spring-security-web-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177) [spring-security-web-5.0.0.M5.jar!/:5.0.0.M5]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357) [spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270) [spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108) [spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) [spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.0.RELEASE.jar!/:5.0.0.RELEASE]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.router.ClientCertificateMapper.doFilter(ClientCertificateMapper.java:77) [client_certificate_mapper-1.1.0_RELEASE.jar!/:1.1.0.RELEASE]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_141]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_141]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 2017-10-12 18:49:28.503 DEBUG 14 --- [nio-8080-exec-6] .w.AuthorizationCodeAuthenticationFilter : Updated SecurityContextHolder to contain null Authentication
   2017-10-13T03:49:28.50+0900 [APP/PROC/WEB/0] OUT 2017-10-12 18:49:28.504 DEBUG 14 --- [nio-8080-exec-6] .w.AuthorizationCodeAuthenticationFilter : Delegating to authentication failure handler org.springframework.security.web.authentication.SimpleUrlAuthenticationFailureHandler@242cf4ce
```

From this log, i can guess that redirect url matching in the following code is against
`https://example.com/foo` and `https://example.com:443/foo` which are different string but mean same.

https://github.com/spring-projects/spring-security/blob/97c938e7f3fd3d8c5de9c56e88058043bb91fef2/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/authentication/AuthorizationCodeAuthenticationProvider.java#L85

This matching logic should be more robust.

### Actual Behavior

Redirect fails.

### Expected Behavior

Redirect succeeds.

### Version

Spring Security 5.0.0.M5 with Spring Boot 2.0.0.M5

**Comment by making** [comment]
I sent pull request #4626 . I've checked this code worked in the environment above.
I'll add some test cases later.

**Comment by rwinch** [comment]
Thanks for the report and the PR. I commented on the PR that this looks like a proxy server configuration and why we don't use `UriComponents` in Spring Security. Please try and fix that setup. If you continue to have issues, please reopen this issue.
