### ISSUE TITLE
AD connection exception: throw InternalAuthenticationServiceException

### ISSUE THREAD

**Issue by TheBoegl** [spring-projects/spring-security#4974]
### Summary
The documentation of the InternalAuthenticationServiceException states it may be thrown if a backend authentication repository is not available. The current (5.0.0.RELEASE) implementation of the ActiveDirectoryLdapAuthenticationProvider fails to do this.

### Actual Behavior

Currently the _javax.naming.CommunicationException_ is converted to a _org.springframework.ldap.CommunicationException_ which is thrown out of the `ProviderManager#authenticate(Authentication)` and does not authenticate against other authentication providers.

A failing authentication request looks like:
```
org.springframework.ldap.CommunicationException: dc.example.com:389; nested exception is javax.naming.CommunicationException: dc.example.com:389 [Root exception is java.net.ConnectException: Connection refused: connect]
	at org.springframework.ldap.support.LdapUtils.convertLdapException(LdapUtils.java:108)
	at org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider.bindAsUser(ActiveDirectoryLdapAuthenticationProvider.java:212)
	at org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider.doAuthentication(ActiveDirectoryLdapAuthenticationProvider.java:144)
	at org.springframework.security.ldap.authentication.AbstractLdapAuthenticationProvider.authenticate(AbstractLdapAuthenticationProvider.java:85)
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:174)
```

### Expected Behavior

A refused connection should not fail that fast and the provider manager should try to authenticate against other authentication providers before throwing the InternalAuthenticationServiceExceptions.

### Version

5.0.0.RELEASE

**Comment by jzheaux** [comment]
Duplicates https://github.com/spring-projects/spring-security/issues/2884
