### ISSUE TITLE
Spring security web in java 9 named module

### ISSUE THREAD

**Issue by timbog** [spring-projects/spring-security#5069]
### Summary

I am trying to run a spring-boot app with spring-security WebSecurityConfigurerAdapter in named module (Java 9) and getting exception
`java.lang.UnsupportedOperationException: ResourceBundle.Control not supported in named modules
	at java.base/java.util.ResourceBundle.checkNamedModule(ResourceBundle.java:1537) ~[na:na]
	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:1498) ~[na:na]
	at spring.context@5.0.4.RELEASE/org.springframework.context.support.ResourceBundleMessageSource.doGetBundle(ResourceBundleMessageSource.java:223) ~[spring-context-5.0.4.RELEASE.jar:na]
	at spring.context@5.0.4.RELEASE/org.springframework.context.support.ResourceBundleMessageSource.getResourceBundle(ResourceBundleMessageSource.java:189) ~[spring-context-5.0.4.RELEASE.jar:na]
	at spring.context@5.0.4.RELEASE/org.springframework.context.support.ResourceBundleMessageSource.resolveCodeWithoutArguments(ResourceBundleMessageSource.java:132) ~[spring-context-5.0.4.RELEASE.jar:na]
	at spring.context@5.0.4.RELEASE/org.springframework.context.support.AbstractMessageSource.getMessageInternal(AbstractMessageSource.java:212) ~[spring-context-5.0.4.RELEASE.jar:na]
	at spring.context@5.0.4.RELEASE/org.springframework.context.support.AbstractMessageSource.getMessage(AbstractMessageSource.java:141) ~[spring-context-5.0.4.RELEASE.jar:na]
	at spring.context@5.0.4.RELEASE/org.springframework.context.support.MessageSourceAccessor.getMessage(MessageSourceAccessor.java:87) ~[spring-context-5.0.4.RELEASE.jar:na]
	at spring.security.web@5.0.3.RELEASE/org.springframework.security.web.access.ExceptionTranslationFilter.handleSpringSecurityException(ExceptionTranslationFilter.java:187) ~[spring-security-web-5.0.3.RELEASE.jar:na]
	at spring.security.web@5.0.3.RELEASE/org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:138) ~[spring-security-web-5.0.3.RELEASE.jar:na]
	at spring.security.web@5.0.3.RELEASE/org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.3.RELEASE.jar:na]
	at spring.security.web@5.0.3.RELEASE/org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) ~[spring-security-web-5.0.3.RELEASE.jar:na]
	at spring.security.web@5.0.3.RELEASE/org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.3.RELEASE.jar:na]
	at spring.security.web@5.0.3.RELEASE/org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) ~[spring-security-web-5.0.3.RELEASE.jar:na]
	at spring.security.web@5.0.3.RELEASE/org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.3.RELEASE.jar:na]
	at spring.security.web@5.0.3.RELEASE/org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170) ~[spring-security-web-5.0.3.RELEASE.jar:na]
	at spring.security.web@5.0.3.RELEASE/org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.3.RELEASE.jar:na]
	at spring.security.web@5.0.3.RELEASE/org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.0.3.RELEASE.jar:na]
	at spring.security.web@5.0.3.RELEASE/org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.3.RELEASE.jar:na]
	at spring.security.web@5.0.3.RELEASE/org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[spring-security-web-5.0.3.RELEASE.jar:na]
	at spring.security.web@5.0.3.RELEASE/org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.3.RELEASE.jar:na]
`
Are there plans to support spring-security to work in named Java 9 module?
 My build.gradle dependencies are
`dependencies {
    final def springVersion='5.0.4.RELEASE'
    final def springSecurityVersion='5.0.3.RELEASE'
    final def springBootVersion='2.0.0.RELEASE'
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile (group: 'org.springframework', name: 'spring-webmvc', version: springVersion) {
        exclude group: 'commons-logging', module: 'commons-logging'
    }
    compile group: 'org.springframework.security', name: 'spring-security-core', version: springSecurityVersion
    compile group: 'org.springframework.security', name: 'spring-security-config', version: springSecurityVersion
    compile(group: "org.springframework.boot", name: "spring-boot-starter-web", version: springBootVersion) {
        exclude group: 'commons-logging', module: 'commons-logging'
        exclude group: 'javax.annotation', module: 'javax.annotation-api'
    }
    compile (group: 'org.springframework.boot', name: 'spring-boot-starter-security', version: springBootVersion) {
        exclude group: 'javax.annotation', module: 'javax.annotation-api'
    }
}`, 
WebSecurityConfigurerAdapter is
`package com.company.getworks.security;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

@Configuration
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Bean
    public PasswordEncoder encoder() {
        return new BCryptPasswordEncoder();
    }

    @Override
    public void configure(final HttpSecurity http) throws Exception {
        http.antMatcher("/**").authorizeRequests().anyRequest().authenticated();
    }
}
`

**Comment by jzheaux** [comment]
Spring Security is using Spring Framework's support for resource bundles, which does, indeed use `ResourceBundle.Control` in the way described at [in ResourceBundle's javadoc](https://docs.oracle.com/javase/9/docs/api/java/util/ResourceBundle.html#bundleprovider):

> ResourceBundle.Control is not supported in named modules. If the getBundle method with a ResourceBundle.Control is called in a named module, the method will throw an UnsupportedOperationException. 

Perhaps there is a preferred way to use Spring's ResourceBundle support in Java 9+ runtimes.

**Comment by rwinch** [comment]
See https://jira.spring.io/projects/SPR/issues/SPR-16776
