### ISSUE TITLE
Possible NPE in org.springframework.security.oauth2.core.ClaimAccessor

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#5608]
**Moved here from [spring-security-oauth/issues/1441](https://github.com/spring-projects/spring-security-oauth/issues/1441)**

There's a possible NullPointerException hidden in `org.springframework.security.oauth2.core.ClaimAccessor.getClaimAsString`:
If the requested claim evaluates to the value `null`, the `toString()` call will fail with a NPE.

Example:

    OAuth2AuthenticationToken extToken; // from spring-securty-oauth2-client
    OAuth2User extUser = extToken.getPrincipal();
    Map<String, Object> userInfoAttributes = extUser.getAttributes();
    OidcUserInfo userInfo = new OidcUserInfo(userInfoAttributes);
    String familyName = userInfo.getFamilyName();

In this case, the `userInfo` response contains some attribute with `null` values, like `family_name`. (I'm not sure if that behavior is valid in OpenId Connect; beside from that it's valid JSON. The provider of that response is some custom piece of software.)

The `OAuth2AuthenticationToken` from the log file:

    [org.springframework.security.web.access.intercept.FilterSecurityInterceptor] Previously 
    Authenticated: org.springframework.security.oauth2.client.authentication.OAuth2AuthenticationToken@3c22eef2: Principal: Name: [some_id], Granted Authorities: [ROLE_USER], 
    User Attributes: [sub=some_id, name=null, preferred_username=non_null, given_name=null, family_name=null, email=test@example.com]; Credentials: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: ROLE_USER

The Exception:

    [com.example.GenericExceptionHandler] java.lang.NullPointerException
        at org.springframework.security.oauth2.core.ClaimAccessor.getClaimAsString(ClaimAccessor.java:61)
        at org.springframework.security.oauth2.core.oidc.StandardClaimAccessor.getFamilyName(StandardClaimAccessor.java:71)
        at com.example.ExternalRegisterController.startCreateNewAccountFromClientRegistration(ExternalRegisterController.java:177)
        at sun.reflect.GeneratedMethodAccessor529.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:870)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:776)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)

Maybe `org.springframework.security.oauth2.core.ClaimAccessor.containsClaim(String)` should check for `null`-values, too; or `org.springframework.security.oauth2.core.oidc.OidcUserInfo.OidcUserInfo(Map<String, Object>)` should omit such values.

Happend in spring-security-oauth2-core-5.0.3.

**Comment by jgrandja** [comment]
Thanks for the report @jbiblio. This fix is now in master.
