### ISSUE TITLE
WhitelistTypeIdResolver should include LinkedHashSet?

### ISSUE THREAD

**Issue by beku8** [spring-projects/spring-security#5852]
After upgrading to spring security 5.0, I started getting the json serialization exceptions such as:

```
Caused by: java.lang.IllegalArgumentException: The class with java.util.LinkedHashSet and name of java.util.LinkedHashSet is not whitelisted. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or by providing a Mixin. If the serialization is only done by a trusted source, you can also enable default typing. See https://github.com/spring-projects/spring-security/issues/4370 for details
	at org.springframework.security.jackson2.SecurityJackson2Modules$WhitelistTypeIdResolver.typeFromId(SecurityJackson2Modules.java:209) ~[spring-security-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:156) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:97) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromArray(AsArrayTypeDeserializer.java:53) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserializeWithType(StringCollectionDeserializer.java:249) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:136) ~[jackson-databind-2.9.6.jar:2.9.6]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.6.jar:2.9.6]
	... 96 common frames omitted
```

New ```WhitelistTypeIdResolver``` seems to make it quite annoying for json serializations. I think we should whitelist most of the common java types(e.g LinkedHashSet). Or at lease provide a documentation on how to work around. This is how I'm "whitelisting" these classes, which was not easy to figure out without any documentation:

```
public class MySecurityModule extends SimpleModule {
@Override
  public void setupModule(SetupContext context) {
    
    context.setMixInAnnotations(LinkedHashSet.class, ArrayWhitelistMixin.class);
  }

@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.WRAPPER_ARRAY)
  abstract class ArrayWhitelistMixin {
    
  }
}

```

My use case was for spring session, so finally I'm registering the module like this:

```
public class SsoSessionRedisConfig implements BeanClassLoaderAware {

  private ClassLoader loader;
	
  ObjectMapper objectMapper() {
    ObjectMapper mapper = new ObjectMapper();
    mapper.registerModules(SecurityJackson2Modules.getModules(this.loader));
    mapper.registerModules(new MySecurityModule());
    return mapper;
  }
	
 @Override
  public void setBeanClassLoader(ClassLoader classLoader) {
    this.loader = classLoader;
  }
	
 @Bean
  public RedisSerializer<Object> springSessionDefaultRedisSerializer() {
    return new GenericJackson2JsonRedisSerializer(objectMapper());
  }
	

}
```

**Comment by rwinch** [comment]
Unless it is a class used by Spring Framework related classes, it is expected behavior to ensure that you do not have any deserialization security vulnerabilties. If you do not like it, you explicitly opt into serializing all classes using something like:

```java
ObjectMapper mapper = new ObjectMapper();
mapper.enableDefaultTyping(ObjectMapper.DefaultTyping.NON_FINAL, JsonTypeInfo.As.PROPERTY);
mapper.registerModules(SecurityJackson2Modules.getModules(loader));
```
Otherwise, you may explicitly register classes that are whitelisted.
