### ISSUE TITLE
Can't login use google account with client-authentication-method=basic

### ISSUE THREAD

**Issue by jinqinghua** [spring-projects/spring-security#5906]
### Can't login use google account with client-authentication-method=basic

I develop a feature that support 3rd-party login use spring boot 2.0.4(spring security 5.0.7)
it work well, but today(**27 sep 2018**), we cant login with google account. 

error stack:
java.lang.IllegalArgumentException: errorCode cannot be empty
 at org.springframework.util.Assert.hasText(Assert.java:276) ~[spring-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
 at org.springframework.security.oauth2.core.OAuth2Error.<init>(OAuth2Error.java:60) ~[spring-security-oauth2-core-5.0.7.RELEASE.jar:5.0.7.RELEASE]
 at org.springframework.security.oauth2.client.endpoint.NimbusAuthorizationCodeTokenResponseClient.getTokenResponse(NimbusAuthorizationCodeTokenResponseClient.java:115) ~[spring-security-oauth2-client-5.0.7.RELEASE.jar:5.0.7.RELEASE]
 at org.springframework.security.oauth2.client.endpoint.NimbusAuthorizationCodeTokenResponseClient.getTokenResponse(NimbusAuthorizationCodeTokenResponseClient.java:67) ~[spring-security-oauth2-client-5.0.7.RELEASE.jar:5.0.7.RELEASE]
 at com.cisco.webex.globalpage.configuration.WebexOidcAuthorizationCodeAuthenticationProvider.authenticate(WebexOidcAuthorizationCodeAuthenticationProvider.java:147) ~[classes/:?]
 at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:174) ~[spring-security-core-5.0.7.RELEASE.jar:5.0.7.RELEASE]

I found google return following json string when we send data to https://www.googleapis.com/oauth2/v4/token
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}

follow the doc: section 4. Exchange code for access token and ID token of : [https://developers.google.com/identity/protocols/OpenIDConnect](https://developers.google.com/identity/protocols/OpenIDConnect)  
I use postman post data with client_id and client_secret, it works. I  found that spring security use 
client-authentication-method=basic as default method, I change it to "post", it works.

so I add a configuration to application.properties:
spring.security.oauth2.client.registration.google.client-authentication-method=post

I want to know:  is google change the server side behavior?

### Actual Behavior

Can't login with google account

### Expected Behavior

Can login with google account

### Configuration

**spring.security.oauth2.client.registration.google.client-authentication-method=post**

### Version

spring boot 2.0.4(spring security 5.0.7)

### Sample
N/A

**Comment by jinqinghua** [comment]
it works well today when use
spring.security.oauth2.client.registration.google.client-authentication-method=basic

close issue.
