### ISSUE TITLE
An invalid remember-me cookie should throw a RememberMeAuthenticationException

### ISSUE THREAD

**Issue by heruan** [spring-projects/spring-security#6910]
### Summary

If an invalid remember-me token is provided by a counterfeit cookie, an `IllegalArgumentException` is thrown:

```
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 1 in: "3J"
	at java.base/java.net.URLDecoder.decode(URLDecoder.java:232) ~[na:na]
	at java.base/java.net.URLDecoder.decode(URLDecoder.java:142) ~[na:na]
	at org.springframework.security.web.authentication.rememberme.AbstractRememberMeServices.decodeCookie(AbstractRememberMeServices.java:242) ~[spring-security-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.security.web.authentication.rememberme.AbstractRememberMeServices.autoLogin(AbstractRememberMeServices.java:135) ~[spring-security-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:98) ~[spring-security-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	
```
### Expected Behavior

A `RememberMeAuthenticationException` is thrown.

### Version

`spring-security-web-5.1.5.RELEASE.jar:5.1.5.RELEASE`

**Comment by jzheaux** [comment]
@heruan I think it would be better to throw `InvalidCookieException` since that is what is thrown in other malformed circumstances in the method.

Would you like to submit a PR for this?

**Comment by heruan** [comment]
Sure! Currently, the only exception which is caught is `UnsupportedEncodingException` and it's just logged. I'd generalize the type to be just `Exception` or add `InvalidArgumentException` to the existing catch clause, so that the invalid part is skipped; then, it's the caller responsibility to check the length of the returned array to be compliant and throw otherwise, e.g. in 
https://github.com/spring-projects/spring-security/blob/b93528138e2b2f7ad34d10a040e6b7ac50fc587a/web/src/main/java/org/springframework/security/web/authentication/rememberme/PersistentTokenBasedRememberMeServices.java#L95-L98
