### ISSUE TITLE
SEC-433: Fix to SEC-359 has introduced a NullPointer to TokenBasedRememberMeServices.logout()

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#694]
["Tim Lenz":https://jira.spring.io/secure/ViewProfile.jspa?name=seabamirum](Migrated from ["SEC-433":https://jira.spring.io/browse/SEC-433?redirect=false]) said:

cancelCookie(request, response, "Logout of user " + authentication.getName()); <-- NULL POINTER if authentication is null

Stack trace: java.lang.NullPointerException
    at org.acegisecurity.ui.rememberme.TokenBasedRememberMeServices.logout(TokenBasedRememberMeServices.java:295)
    at org.acegisecurity.ui.logout.LogoutFilter.doFilter(LogoutFilter.java:98)
    at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:274)
    at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:229)
    at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:274)
    at org.acegisecurity.securechannel.ChannelProcessingFilter.doFilter(ChannelProcessingFilter.java:138)
    at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:274)
    at org.acegisecurity.util.FilterChainProxy.doFilter(FilterChainProxy.java:148)
    at org.acegisecurity.util.FilterToBeanProxy.doFilter(FilterToBeanProxy.java:98)

**Comment by spring-issuemaster** [comment]
This issue duplicates #668
