### ISSUE TITLE
Hex-encoded string must have an even number of characters

### ISSUE THREAD

**Issue by jpfss** [spring-projects/spring-security#6975]
### the pom file config as follows:
```xml

    <properties>
        <spring.boot.version>2.1.5</spring.boot.version>
    </properties>
<dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-security</artifactId>
                <version>${spring.boot.version}.RELEASE</version>
            </dependency>
   <repositories>
        <!-- ... possibly other repository elements ... -->
        <repository>
            <id>spring-milestone</id>
            <name>Spring Milestone Repository</name>
            <url>https://repo.spring.io/milestone</url>
        </repository>
    </repositories>
```

The Oracle JDK's Version is 1.11

### code as follows:
```java  
public static void main(String[] args) throws UnsupportedEncodingException {

        String salt = "salt";
        BytesEncryptor bytesEncryptor = Encryptors.standard("password", salt);

    }
```

### Actual Behavior
```java
Connected to the target VM, address: '127.0.0.1:27335', transport: 'socket'
Exception in thread "main" java.lang.IllegalArgumentException: Detected a Non-hex character at 1 or 2 position
	at org.springframework.security.crypto.codec.Hex.decode(Hex.java:62)
	at org.springframework.security.crypto.encrypt.AesBytesEncryptor.<init>(AesBytesEncryptor.java:102)
	at org.springframework.security.crypto.encrypt.AesBytesEncryptor.<init>(AesBytesEncryptor.java:97)
	at org.springframework.security.crypto.encrypt.Encryptors.standard(Encryptors.java:66)
	at cn.itcast.research.plab.util.SMSV2SendUtilsTest.main(SMSV2SendUtilsTest.java:30)
Disconnected from the target VM, address: '127.0.0.1:27335', transport: 'socket'
```

### Reasons that I think are possible  
The class Hex in  package "package org.springframework.security.crypto.codec;".
```java

	public static byte[] decode(CharSequence s) {
		int nChars = s.length();

		if (nChars % 2 != 0) {
			throw new IllegalArgumentException(
					"Hex-encoded string must have an even number of characters");
		}

		byte[] result = new byte[nChars / 2];

		for (int i = 0; i < nChars; i += 2) {
			int msb = Character.digit(s.charAt(i), 16);
			int lsb = Character.digit(s.charAt(i + 1), 16);

			if (msb < 0 || lsb < 0) {
				throw new IllegalArgumentException(
					"Detected a Non-hex character at " + (i + 1) + " or " + (i + 2) + " position");
			}
			result[i / 2] = (byte) ((msb << 4) | lsb);
		}
		return result;
	}
```

**Comment by rwinch** [comment]
You need to ensure that the salt that you passed in is Hex encoded [as specified on the Javadoc](https://docs.spring.io/spring-security/site/docs/5.1.x/api/org/springframework/security/crypto/encrypt/Encryptors.html#standard-java.lang.CharSequence-java.lang.CharSequence-).

**Comment by jpfss** [comment]
Thank you ,That's ok.
