### ISSUE TITLE
Revert to org.aspectj 1.9.3

### ISSUE THREAD

**Issue by eleftherias** [spring-projects/spring-security#7001]
### Summary

Revert to org.aspectj 1.9.3

**Comment by eleftherias** [comment]
Aspectj needs to be reverted from 1.9.4 to 1.9.3 because the newer version breaks our build with the following error:
```
java.lang.IllegalStateException: Unexpectedly unable to initialize a JRT filesystem
	at org.aspectj.weaver.bcel.ClassPathManager$JImageEntry.<init>(ClassPathManager.java:370)
	at org.aspectj.weaver.bcel.ClassPathManager.addPath(ClassPathManager.java:113)
	at org.aspectj.weaver.bcel.ClassPathManager.<init>(ClassPathManager.java:87)
	at org.aspectj.weaver.bcel.BcelWorld.<init>(BcelWorld.java:285)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.initBcelWorld(AjBuildManager.java:841)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:253)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:189)
	at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:114)
	at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
	at org.aspectj.tools.ajc.Main.run(Main.java:371)
	at org.aspectj.tools.ajc.Main.runMain(Main.java:248)
	at org.aspectj.tools.ajc.Main.main(Main.java:84)
```
