### ISSUE TITLE
Update CAS sample to use cas-server-webapp 4.2.7

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#7213]
Spring Security already depends on `cas-server-webapp:4.2.7`; however, the casserver module uses 4.0.0:

```gradle
dependencies {
        compile "org.jasig.cas:cas-server-webapp:4.0.0@war"
        // ...
}
```

When upgrading to 4.2.7, the server appears to fail to start up, caused by the exception:

```
Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'allowedToProxy' of bean class [org.jasig.cas.services.RegexRegisteredService]: Bean property 'allowedToProxy' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
        at org.springframework.beans.BeanWrapperImpl.createNotWritablePropertyException(BeanWrapperImpl.java:230)
        at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:423)
        at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:280)
        at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:95)
        at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:75)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1518)
        ... 92 more
```

**Comment by rwinch** [comment]
Samples have moved to https://github.com/spring-projects/spring-security-samples
