### ISSUE TITLE
SEC-464: NPE when missing 'j_acegi_logout' when not logged in

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#725]
["Corba the Geek":https://jira.spring.io/secure/ViewProfile.jspa?name=corbathegeek](Migrated from ["SEC-464":https://jira.spring.io/browse/SEC-464?redirect=false]) said:

I receive a NPE Null PointerException when linking to 'j_acegi_logout':

```
<a href="<c:url value="/j_acegi_logout"/>">Logoff</a>
```

when there is no user currently logged in

Here is the stack trace for the exception:

An Error has occurred in this application.

java.lang.NullPointerException
    at org.acegisecurity.ui.rememberme.TokenBasedRememberMeServices.logout(TokenBasedRememberMeServices.java:295)
    at org.acegisecurity.ui.logout.LogoutFilter.doFilter(LogoutFilter.java:98)
    at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:274)
    at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:229)
    at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:274)
    at org.acegisecurity.util.FilterChainProxy.doFilter(FilterChainProxy.java:148)
    at org.acegisecurity.util.FilterToBeanProxy.doFilter(FilterToBeanProxy.java:98)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:78)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:77)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)
    at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)
    at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
    at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
    at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
    at java.lang.Thread.run(Thread.java:595)

My current workaround for the problem is to wrap the "logout" link with <authz/> tags:

```
<authz:authorize ifAnyGranted="ROLE_USER,ROLE_ADMINISTRATOR">
    <a href="<c:url value="/j_acegi_logout"/>">Logoff</a>
</authz:authorize>
```

which prevents the "Logoff" link from showing, but does not stop a user from manually entering the 'j_acegi_logout' link themselves.

Here is the filterChainProxy config:

```
<bean id="filterChainProxy" class="org.acegisecurity.util.FilterChainProxy">
    <property name="filterInvocationDefinitionSource">
        <value>
            CONVERT_URL_TO_LOWERCASE_BEFORE_COMPARISON
            PATTERN_TYPE_APACHE_ANT
            /images/**=#NONE#
            /scripts/**=#NONE#
            /styles/**=#NONE#
            /**=httpSessionContextIntegrationFilter,logoutFilter,authenticationProcessingFilter,securityContextHolderAwareRequestFilter,rememberMeProcessingFilter,anonymousProcessingFilter,exceptionTranslationFilter,filterInvocationInterceptor
        </value>
        <!-- :TODO: Put channelProcessingFilter before securityContextHolderAwareRequestFilter to turn on SSL switching -->
        <!-- It's off by default b/c Canoo WebTest doesn't support SSL out-of-the-box -->
    </property>
</bean>
```

Here is the logoutFilter config:

```
<bean id="logoutFilter" class="org.acegisecurity.ui.logout.LogoutFilter">
  <constructor-arg value="/"/> <!-- URL redirected to after logout -->
  <constructor-arg>
     <list>
          <ref bean="rememberMeServices"/>
          <bean class="org.acegisecurity.ui.logout.SecurityContextLogoutHandler"/>
     </list>
  </constructor-arg>
</bean>
```

**Comment by spring-issuemaster** [comment]
This issue duplicates #668
