### ISSUE TITLE
SecurityJackson2Modules attempts to pull in modules not necessarily on the classpath

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-security#7520]
Spring Session for MongoDB, in it's Jackson converter setup, delegates to Spring Security to register Spring Security types with the following code:

```java
private ObjectMapper buildObjectMapper() {

	ObjectMapper objectMapper = new ObjectMapper();

	// serialize fields instead of properties
	objectMapper.setVisibility(PropertyAccessor.ALL, JsonAutoDetect.Visibility.NONE);
	objectMapper.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY);

	// ignore unresolved fields (mostly 'principal')
	objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

	objectMapper.setPropertyNamingStrategy(new MongoIdNamingStrategy());

	objectMapper.registerModules(SecurityJackson2Modules.getModules(getClass().getClassLoader()));
	objectMapper.addMixIn(MongoSession.class, MongoSessionMixin.class);
	objectMapper.addMixIn(HashMap.class, HashMapMixin.class);

	return objectMapper;
}
```

By invoking `SecurityJackson2Modules.getModules()`, it is leveraging Spring Security's awareness of types to properly whitelist these types.

A recent test case was written that required pulling in WebFlux security (in test scope) as shown below:

```xml
<dependency>
	<groupId>org.springframework.security</groupId>
	<artifactId>spring-security-config</artifactId>
	<scope>test</scope>
</dependency>

<dependency>
	<groupId>org.springframework.security</groupId>
	<artifactId>spring-security-web</artifactId>
	<scope>test</scope>
</dependency>
```

This made another unit test fail with this:

```
09:46:12.609 [    main] DEBUG o.s.s.j.SecurityJackson2Modules - Loaded module org.springframework.security.jackson2.CoreJackson2Module, now registering
09:46:12.614 [    main] DEBUG o.s.s.j.SecurityJackson2Modules - Cannot load module org.springframework.security.cas.jackson2.CasJackson2Module
java.lang.ClassNotFoundException: org.springframework.security.cas.jackson2.
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:277)
	at org.springframework.security.jackson2.SecurityJackson2Modules.loadAndGetInstance(SecurityJackson2Modules.java:93)
	at org.springframework.security.jackson2.SecurityJackson2Modules.addToModulesList(SecurityJackson2Modules.java:129)
	at org.springframework.security.jackson2.SecurityJackson2Modules.getModules(SecurityJackson2Modules.java:115)
	at org.springframework.session.data.mongo.JacksonMongoSessionConverter.buildObjectMapper(JacksonMongoSessionConverter.java:102)
```

With `spring-security-cas` NOT on the classpath, this shouldn't be an issue. However, the attempt to pull in `CasJackson2Module` unconditionally makes this test case break.

Spring Security should try to pull in these components, but not fail if they don't exist.

NOTE: This happens both on Spring Security **5.1.6.RELEASE** (our currently used version) as well as on Spring Security **5.2.0.RELEASE**. Thus, fixing on both `5.1.x` and on `5.2.x` would be a good thing.

**Comment by gregturn** [comment]
Turns out, the stack trace is simply a trace debug log statement. It doesn't actually fail here.
