### ISSUE TITLE
Blockhound fails on Webflux Security in Java 8,11 and 12, but not 13

### ISSUE THREAD

**Issue by MaxPowerDarrel** [spring-projects/spring-security#7522]
### Summary

The same Kotlin code (included) returns a 500 because block hound detects blocking code (FileInputStream.readBytes) when run against Oracle JDK 1.8.0_181.  Only changing the runtime to OpenJDK 13, and no changes to the code, the same call is successful.

### Version

SpringBoot 2.2.RC1 (Spring Security 5.2)

### Sample

https://github.com/MaxPowerDarrel/documents

**Comment by dlsrb6342** [comment]
Is there any updates on this issue? 
I have same problem. 

Java 11
Spring Security 5.2.1.RELEASE
Spring boot 2.2.1.RELEASE

**Comment by rwinch** [comment]
The sample is gone. Can you provide a sample?

**Comment by dlsrb6342** [comment]
https://github.com/dlsrb6342/spring-security-blockhound

I pushed example.
Please check `WithBlockHoundTest` and `WithoutBlockHoundTest`.
With BlockHound, all tests are failed.

**Comment by dlsrb6342** [comment]
@rwinch Please have a look my example.

**Comment by rwinch** [comment]
Thanks for the report. Spring Security [AbstractUserDetailsReactiveAuthenticationManager uses publishOn](https://github.com/spring-projects/spring-security/blob/5.3.2.RELEASE/core/src/main/java/org/springframework/security/authentication/AbstractUserDetailsReactiveAuthenticationManager.java#L102) `Schedulers.newParallel` before it [encodes the password](https://github.com/spring-projects/spring-security/blob/5.3.2.RELEASE/core/src/main/java/org/springframework/security/authentication/AbstractUserDetailsReactiveAuthenticationManager.java#L109) so I don't think this should happen. I can confirm that the Thread being used for encoding is `password-encoder-*` thread name.

```
reactor.blockhound.BlockingOperationError: Blocking call! java.io.FileInputStream#readBytes
	at java.base/java.io.FileInputStream.readBytes(FileInputStream.java) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.security.test.web.reactive.server.SecurityMockServerConfigurers$MutatorFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP GET "/controller" [ExceptionHandlingWebHandler]
Stack trace:
		at java.base/java.io.FileInputStream.readBytes(FileInputStream.java) ~[na:na]
		at java.base/java.io.FileInputStream.read(FileInputStream.java:279) ~[na:na]
		at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133) ~[na:na]
		at java.base/sun.security.provider.NativePRNG$RandomIO.readFully(NativePRNG.java:424) ~[na:na]
		at java.base/sun.security.provider.NativePRNG$RandomIO.ensureBufferValid(NativePRNG.java:526) ~[na:na]
		at java.base/sun.security.provider.NativePRNG$RandomIO.implNextBytes(NativePRNG.java:545) ~[na:na]
		at java.base/sun.security.provider.NativePRNG.engineNextBytes(NativePRNG.java:220) ~[na:na]
		at java.base/java.security.SecureRandom.nextBytes(SecureRandom.java:741) ~[na:na]
		at org.springframework.security.crypto.bcrypt.BCrypt.gensalt(BCrypt.java:832) ~[spring-security-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
		at org.springframework.security.crypto.bcrypt.BCrypt.gensalt(BCrypt.java:856) ~[spring-security-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
		at org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder.encode(BCryptPasswordEncoder.java:106) ~[spring-security-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
		at org.springframework.security.crypto.password.DelegatingPasswordEncoder.encode(DelegatingPasswordEncoder.java:186) ~[spring-security-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
		at org.springframework.security.authentication.AbstractUserDetailsReactiveAuthenticationManager.lambda$authenticate$4(AbstractUserDetailsReactiveAuthenticationManager.java:109) ~[spring-security-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE]
		at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:107) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE]
		at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:178) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE]
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
		at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

```

A simplified test is

```java
    @Test
    void blockhoundFailsWithParallelScheduler() {
        Scheduler passwordEncoderScheduler = Schedulers.newParallel("password-encoder", Schedulers.DEFAULT_POOL_SIZE, true);
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
        Mono.delay(Duration.ofSeconds(1))
            .publishOn(passwordEncoderScheduler)
            .doOnNext(it -> {
                System.out.println(Thread.currentThread().getName());
                encoder.encode("hi");
            })
            .block();
    }
```

Perhaps @bsideup can help out here?

**Comment by bsideup** [comment]
@rwinch `Schedulers.newParallel` will pass `true` to `rejectBlocking` of `ReactorThreadFactory`:
https://github.com/reactor/reactor-core/blob/a8022380f7d1eb9ef5bdcf0a9e0366d3dad534df/reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java#L520-L524

Consider either using `newParallel(int parallelism, ThreadFactory threadFactory)` or `newBoundedElastic(Schedulers.DEFAULT_POOL_SIZE, queueSizePerThread)`

**Comment by rwinch** [comment]
@bsideup Why does it do that? Is this actually broken? Do we need to change our behavior?

**Comment by bsideup** [comment]
Because `parallel` schedulers are considered for non-blocking stuff (given the very low number of threads).

BTW just realized that there is a 3rd option:
```java
Schedulers.fromExecutor(Executors.newFixedThreadPool(Schedulers.DEFAULT_POOL_SIZE))
```

**Comment by rwinch** [comment]
After speaking with @bsideup offline, we should be using `Schedulers.boundidElastic()` since there are some JDKs which use blocking operations.

**Comment by dlsrb6342** [comment]
@rwinch 
Thank you for quick response. 
Can I know when this changes is released?

**Comment by rwinch** [comment]
It will be released on June 3

FYI: You can click on any of the backported issues above and view the milestone and see when it is scheduled.
