### ISSUE TITLE
Improve handling of invalid tokens

### ISSUE THREAD

**Issue by guykoth** [spring-projects/spring-security#7677]
### Summary

When using the AuthenticationPrincipal annotation in a ResourceServer  and passing an invalid JWT  (bad signature) in a controller signature the framework return a generic error 500 where it should return 400 as it is an invalid data from the user. This has previously been reported on [spring-security-oauth](https://github.com/spring-projects/spring-security-oauth/issues/1522) too.

### Actual Behavior

when sending a bad jwt as part of the headers to a controller with an AuthenticationPrincipal annotation the framework returns this stacktrace: 
```
java.lang.RuntimeException: java.security.SignatureException: Signature length not correct: got 38 but was expecting 256
	at org.springframework.security.jwt.crypto.sign.RsaVerifier.verify(RsaVerifier.java:59)
	at org.springframework.security.jwt.JwtImpl.verifySignature(JwtHelper.java:287)
	at org.springframework.security.oauth2.provider.token.store.jwk.JwkVerifyingJwtAccessTokenConverter.decode(JwkVerifyingJwtAccessTokenConverter.java:122)
	at org.springframework.security.oauth2.provider.token.store.JwtTokenStore.convertAccessToken(JwtTokenStore.java:88)
	at org.springframework.security.oauth2.provider.token.store.JwtTokenStore.readAccessToken(JwtTokenStore.java:80)
	at org.springframework.security.oauth2.provider.token.store.jwk.JwkTokenStore.readAccessToken(JwkTokenStore.java:212)
	at org.springframework.security.oauth2.provider.token.DefaultTokenServices.loadAuthentication(DefaultTokenServices.java:229)
	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationManager.authenticate(OAuth2AuthenticationManager.java:83)
	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:150)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:461)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:394)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:253)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:175)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.security.SignatureException: Signature length not correct: got 38 but was expecting 256
	at java.base/sun.security.rsa.RSASignature.engineVerify(RSASignature.java:212)
	at java.base/java.security.Signature$Delegate.engineVerify(Signature.java:1247)
	at java.base/java.security.Signature.verify(Signature.java:675)
	at org.springframework.security.jwt.crypto.sign.RsaVerifier.verify(RsaVerifier.java:54)
	... 42 common frames omitted
```

### Expected Behavior

As it is a client error (providing an invalid token),
It could be improved eg. by catching RuntimeExceptions in JwtTokenStore.readAccessToken and wrapping them in InvalidTokenException

### Configuration

We have a java application that uses oauth 2 to allow access to a controller. we are verifying the JWT in our application to check if the request is allowed to access the resource.
To do this our application is configured as a `ResourceServer` using JWT-encoded bearer tokens.

### Version

spring-boot-starter-parent:2.2.0.RELEASE
spring-boot-starter-oauth2-resource-server:2.2.0.RELEASE
spring-boot-starter-security:2.2.0.RELEASE
spring-boot-starter-web:2.2.0.RELEASE
spring-boot-starter-actuator:2.2.0.RELEASE
spring-security-oauth2-autoconfigure:2.2.0.RELEASE

**Comment by jgrandja** [comment]
@guykoth Please do not double post. This issue belongs in the Spring Security OAuth project so I'll leave [spring-security-oauth#1522](https://github.com/spring-projects/spring-security-oauth/issues/1522) open.
