### ISSUE TITLE
IllegalStateException when session is already invalidated

### ISSUE THREAD

**Issue by kouroups** [spring-projects/spring-security#9127]
In AbstractPreAuthenticatedProcessingFilter.java in the following block of code

`if (AbstractPreAuthenticatedProcessingFilter.this.invalidateSessionOnPrincipalChange) {
				SecurityContextHolder.clearContext();
				HttpSession session = request.getSession(false);
				if (session != null) {
					AbstractPreAuthenticatedProcessingFilter.this.logger.debug("Invalidating existing session");
					session.invalidate();
					request.getSession();
				}
}
`
if the session is not null then the expectation is to invalidate it and get a new session but if the session is already invalidated then an IllegalStateException is thrown and an error is returned to the user. 

Stacktrace: 

`	java.lang.IllegalStateException: invalidate: Session already invalidated
	at org.apache.catalina.session.StandardSession.invalidate(StandardSession.java:1217)
	at org.apache.catalina.session.StandardSessionFacade.invalidate(StandardSessionFacade.java:170)
	at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter$PreAuthenticatedProcessingRequestMatcher.matches(AbstractPreAuthenticatedProcessingFilter.java:372)
	at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:120)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)`

Expectation is to invalidate the session and get a new one so given that session is already invalidate then the exception should be caught and allow it to get a new session

**Comment by jzheaux** [comment]
This seems reasonable, but I'd like to better understand your specific use case. Can you explain under what circumstances the existing session is getting invalidated before it reaches this filter?

**Comment by kouroups** [comment]
Hey Josn,  I tried to reproduce it using various ways but I wasn't able, so I suspect is race conditions. But I see it quite often happening in logs. And looks odd to me to invalidate an existing invalidated session

**Comment by jzheaux** [comment]
Closing due to https://github.com/spring-projects/spring-security/pull/9128#issuecomment-984972101

**Comment by stefan-g** [comment]
@jzheaux  I'm facing the same issue. I have a  restcontroller with a /logout endpoint where the session is invalidated.
The exception does't happen all the time. Is there a way to prevent that the session is saved after it was invalidated? 

Or is the best practive as descibed in this example: https://github.com/jzheaux/spring-security-examples/tree/master/gh-9128?


`java.lang.IllegalStateException: Session was invalidated
	at org.springframework.session.data.redis.RedisSessionRepository.save(RedisSessionRepository.java:129)
	at org.springframework.session.data.redis.RedisSessionRepository.save(RedisSessionRepository.java:45)
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:229)
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:145)
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:82)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
			2 lines skipped for [org.apache.catalina]
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
			2 lines skipped for [org.apache.catalina]
	at ch.deeppay.spring.filter.JsonRequestSizeLimitFilter.doFilterInternal(JsonRequestSizeLimitFilter.java:53)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
			2 lines skipped for [org.apache.catalina]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
			17 lines skipped for [org.apache.catalina, org.apache.tomcat, org.apache.coyote]
	at java.base/java.lang.Thread.run(Thread.java:840)`

**Comment by lrozenblyum** [comment]
The same issue hits us randomly in `HttpSessionSecurityContextRepository.readSecurityContextFromSession`:

```
java.lang.IllegalStateException: getAttribute: Session already invalidated                                                                                          at org.apache.catalina.session.StandardSession.getAttribute(StandardSession.java:1090) ~[tomcat-embed-core-9.0.83.jar!/:?]                                  at org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:101) ~[tomcat-embed-core-9.0.83.jar!/:?]                       at org.springframework.security.web.context.HttpSessionSecurityContextRepository.readSecurityContextFromSession(HttpSessionSecurityContextRepository.java:211) ~[spring-security-web-5.8.12.jar!/:5.8.12]
```
