### ISSUE TITLE
Thread-unsafe usage of HttpServletResponse corrupting jetty HttpFields state in reactive ResponseBodyEmitter handlers

### ISSUE THREAD

**Issue by SpComb** [spring-projects/spring-security#9175]
**Affects:** 5.2.5.RELEASE

---

We have a Spring Web MVC + jetty application using SSE for notifications. We recently converted our SSE controller from returning a `SseEmitter` to returning a `Flux<ServerSentEvent<?>>`, whereupon we started seeing sporadic `NullPointerException`s from jetty `Response.setHeader` calls for something on the order of 0.02% of requests for these SSE endpoints:

```
2020-05-12 11:15:53.837|WARN|1|qtp453671855-27|||org.eclipse.jetty.server.HttpChannel|MAIN||||/...
java.lang.NullPointerException: null
	at org.eclipse.jetty.http.HttpFields.put(HttpFields.java:630) ~[jetty-http-9.4.20.v20190813.jar!/:9.4.20.v20190813]
	at org.eclipse.jetty.http.HttpFields.put(HttpFields.java:658) ~[jetty-http-9.4.20.v20190813.jar!/:9.4.20.v20190813]
	at org.eclipse.jetty.server.Response.setHeader(Response.java:582) ~[jetty-server-9.4.20.v20190813.jar!/:9.4.20.v20190813]
	at javax.servlet.http.HttpServletResponseWrapper.setHeader(HttpServletResponseWrapper.java:203) ~[javax.servlet-api-3.1.0.jar!/:3.1.0]
	at org.springframework.security.web.firewall.FirewalledResponse.setHeader(FirewalledResponse.java:49) ~[spring-security-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.security.web.header.writers.frameoptions.XFrameOptionsHeaderWriter.writeHeaders(XFrameOptionsHeaderWriter.java:99) ~[spring-security-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
   ....
```

Looking at the [jetty `HttpFields` implementation](https://github.com/eclipse/jetty.project/blob/jetty-9.4.20.v20190813/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java#L630), these NPEs seem to be caused by a corrupted internal `_fields` state containing `nulls`.

With jetty 9.4.20 these exceptions cause the connection to be aborted, but with newer version of jetty (at least 9.4.27) these corrupted `HttpFields` put the jetty `HttpChannel` into a busyloop that crashes the entire server: https://github.com/eclipse/jetty.project/issues/4860

Investigating the underlying NPE issue together with the jetty maintainers we were unable to find any direct calls to the jetty APIs that would introduce `null` values in the `HttpFields` state, but looking at the implementation of the jetty `HttpFields` structure used in `Response.setHeaders/addHeaders` etc, it is suspectible to internal state corruption if called concurrently from multiple threads, and is documented as non-threadsafe:

> ```
> * <p>This class is not synchronized as it is expected that modifications will only be performed by a
> * single thread.
> ```

This kind of corruption caused by concurrent multi-threaded accesses also matches up with our observation of very rarely occuring state corruption/crashes. And indeed, using `jdb` to trace calls to these header-related methods for a single HTTP request, I can see calls from multiple different threads!

Some of the calls are from the jetty server thread, via the servlet filter chain, ~which is the correct usage~:

```
  [1] org.eclipse.jetty.server.Response.addHeader (Response.java:627)
  [2] javax.servlet.http.HttpServletResponseWrapper.addHeader (HttpServletResponseWrapper.java:212)
  [3] org.springframework.security.web.firewall.FirewalledResponse.addHeader (FirewalledResponse.java:55)
  [4] javax.servlet.http.HttpServletResponseWrapper.addHeader (HttpServletResponseWrapper.java:212)
  [5] org.springframework.security.web.util.OnCommittedResponseWrapper.addHeader (OnCommittedResponseWrapper.java:63)
  [6] org.springframework.web.cors.DefaultCorsProcessor.processRequest (DefaultCorsProcessor.java:63)
  [7] org.springframework.web.servlet.handler.AbstractHandlerMapping$CorsInterceptor.preHandle (AbstractHandlerMapping.java:582)
  [8] org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle (HandlerExecutionChain.java:141)
  [9] org.springframework.web.servlet.DispatcherServlet.doDispatch (DispatcherServlet.java:1,035)
  [10] org.springframework.web.servlet.DispatcherServlet.doService (DispatcherServlet.java:943)
  [11] org.springframework.web.servlet.FrameworkServlet.processRequest (FrameworkServlet.java:1,006)
  [12] org.springframework.web.servlet.FrameworkServlet.doGet (FrameworkServlet.java:898)
  [13] javax.servlet.http.HttpServlet.service (HttpServlet.java:687)
  [14] org.springframework.web.servlet.FrameworkServlet.service (FrameworkServlet.java:883)
  [15] javax.servlet.http.HttpServlet.service (HttpServlet.java:790)
  [16] org.eclipse.jetty.servlet.ServletHolder.handle (ServletHolder.java:755)
  [17] org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1,617)
  [18] com.example.common.audit.MDCLogFilter.doFilter (MDCLogFilter.java:67)
  [19] org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1,604)
  [20] org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter (FilterChainProxy.java:320)
  [21] org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke (FilterSecurityInterceptor.java:126)
  [22] org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter (FilterSecurityInterceptor.java:90)
  [23] org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter (FilterChainProxy.java:334)
  [24] org.springframework.security.web.access.ExceptionTranslationFilter.doFilter (ExceptionTranslationFilter.java:118)
  [25] org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter (FilterChainProxy.java:334)
  [26] org.springframework.security.web.session.SessionManagementFilter.doFilter (SessionManagementFilter.java:137)
  [27] org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter (FilterChainProxy.java:334)
  [28] org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter (AnonymousAuthenticationFilter.java:111)
  [29] org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter (FilterChainProxy.java:334)
  [30] org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter (SecurityContextHolderAwareRequestFilter.java:158)
  [31] org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter (FilterChainProxy.java:334)
  [32] com.example.common.auth.WhitelistIpAuthenticationFilter.doFilter (WhitelistIpAuthenticationFilter.java:37)
  [33] org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter (FilterChainProxy.java:334)
  [34] org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal (BasicAuthenticationFilter.java:204)
  [35] org.springframework.web.filter.OncePerRequestFilter.doFilter (OncePerRequestFilter.java:119)
  [36] org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter (FilterChainProxy.java:334)
  [37] com.example.common.auth.StatelessAuthenticationFilter.doFilter (StatelessAuthenticationFilter.java:49)
  [38] org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter (FilterChainProxy.java:334)
  [39] org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter (HeaderWriterFilter.java:92)
  [40] org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal (HeaderWriterFilter.java:77)
  [41] org.springframework.web.filter.OncePerRequestFilter.doFilter (OncePerRequestFilter.java:119)
  [42] org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter (FilterChainProxy.java:334)
  [43] org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter (SecurityContextPersistenceFilter.java:105)
  [44] org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter (FilterChainProxy.java:334)
  [45] org.springframework.security.web.FilterChainProxy.doFilterInternal (FilterChainProxy.java:215)
  [46] org.springframework.security.web.FilterChainProxy.doFilter (FilterChainProxy.java:178)
  [47] org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate (DelegatingFilterProxy.java:358)
  [48] org.springframework.web.filter.DelegatingFilterProxy.doFilter (DelegatingFilterProxy.java:271)
  [49] org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1,604)
  [50] org.springframework.web.filter.RequestContextFilter.doFilterInternal (RequestContextFilter.java:100)
  [51] org.springframework.web.filter.OncePerRequestFilter.doFilter (OncePerRequestFilter.java:119)
  [52] org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1,604)
  [53] org.springframework.web.filter.FormContentFilter.doFilterInternal (FormContentFilter.java:93)
  [54] org.springframework.web.filter.OncePerRequestFilter.doFilter (OncePerRequestFilter.java:119)
  [55] org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1,604)
  [56] org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal (WebMvcMetricsFilter.java:109)
  [57] org.springframework.web.filter.OncePerRequestFilter.doFilter (OncePerRequestFilter.java:119)
  [58] org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1,604)
  [59] org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal (CharacterEncodingFilter.java:201)
  [60] org.springframework.web.filter.OncePerRequestFilter.doFilter (OncePerRequestFilter.java:119)
  [61] org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1,604)
  [62] org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:545)
  [63] org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:143)
  [64] org.eclipse.jetty.security.SecurityHandler.handle (SecurityHandler.java:590)
  [65] org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:127)
  [66] org.eclipse.jetty.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:235)
  [67] org.eclipse.jetty.server.session.SessionHandler.doHandle (SessionHandler.java:1,610)
  [68] org.eclipse.jetty.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:233)
  [69] org.eclipse.jetty.server.handler.ContextHandler.doHandle (ContextHandler.java:1,300)
  [70] org.eclipse.jetty.server.handler.ScopedHandler.nextScope (ScopedHandler.java:188)
  [71] org.eclipse.jetty.servlet.ServletHandler.doScope (ServletHandler.java:485)
  [72] org.eclipse.jetty.server.session.SessionHandler.doScope (SessionHandler.java:1,580)
  [73] org.eclipse.jetty.server.handler.ScopedHandler.nextScope (ScopedHandler.java:186)
  [74] org.eclipse.jetty.server.handler.ContextHandler.doScope (ContextHandler.java:1,215)
  [75] org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:141)
  [76] org.eclipse.jetty.server.handler.StatisticsHandler.handle (StatisticsHandler.java:173)
  [77] org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:127)
  [78] org.eclipse.jetty.server.Server.handle (Server.java:500)
  [79] org.eclipse.jetty.server.HttpChannel.lambda$handle$1 (HttpChannel.java:383)
  [80] org.eclipse.jetty.server.HttpChannel$$Lambda$1167.1412565883.dispatch (null)
  [81] org.eclipse.jetty.server.HttpChannel.dispatch (HttpChannel.java:547)
  [82] org.eclipse.jetty.server.HttpChannel.handle (HttpChannel.java:375)
  [83] org.eclipse.jetty.server.HttpConnection.onFillable (HttpConnection.java:273)
  [84] org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:311)
  [85] org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:103)
  [86] org.eclipse.jetty.io.ChannelEndPoint$2.run (ChannelEndPoint.java:117)
  [87] org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask (EatWhatYouKill.java:336)
  [88] org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce (EatWhatYouKill.java:313)
  [89] org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce (EatWhatYouKill.java:171)
  [90] org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce (EatWhatYouKill.java:135)
  [91] org.eclipse.jetty.io.ManagedSelector$$Lambda$1140.431966204.run (null)
  [92] org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:806)
  [93] org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run (QueuedThreadPool.java:938)
  [94] java.lang.Thread.run (Thread.java:834)
```

However, there are also calls to `addHeader` from the `ThreadPoolExecutor` used in the spring framework `ResponseBodyEmitterReturnValueHandler` implementation, via the `org.springframework.web.servlet.mvc.method.annotation.ReactiveTypeHandler$SseEmitterSubscriber`:

```
  [1] org.eclipse.jetty.server.Response.addHeader (Response.java:627)
  [2] javax.servlet.http.HttpServletResponseWrapper.addHeader (HttpServletResponseWrapper.java:212)
  [3] org.springframework.security.web.firewall.FirewalledResponse.addHeader (FirewalledResponse.java:55)
  [4] javax.servlet.http.HttpServletResponseWrapper.addHeader (HttpServletResponseWrapper.java:212)
  [5] org.springframework.security.web.util.OnCommittedResponseWrapper.addHeader (OnCommittedResponseWrapper.java:63)
  [6] org.springframework.http.server.ServletServerHttpResponse.lambda$writeHeaders$0 (ServletServerHttpResponse.java:104)
  [7] org.springframework.http.server.ServletServerHttpResponse$$Lambda$1241.488706756.accept (null)
  [8] java.util.Map.forEach (Map.java:661)
  [9] org.springframework.http.server.ServletServerHttpResponse.writeHeaders (ServletServerHttpResponse.java:102)
  [10] org.springframework.http.server.ServletServerHttpResponse.getBody (ServletServerHttpResponse.java:83)
  [11] org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$StreamingServletServerHttpResponse.getBody (ResponseBodyEmitterReturnValueHandler.java:278)
  [12] org.springframework.http.converter.StringHttpMessageConverter.writeInternal (StringHttpMessageConverter.java:122)
  [13] org.springframework.http.converter.StringHttpMessageConverter.writeInternal (StringHttpMessageConverter.java:44)
  [14] org.springframework.http.converter.AbstractHttpMessageConverter.write (AbstractHttpMessageConverter.java:227)
  [15] org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.sendInternal (ResponseBodyEmitterReturnValueHandler.java:210)
  [16] org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.send (ResponseBodyEmitterReturnValueHandler.java:203)
  [17] org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.sendInternal (ResponseBodyEmitter.java:189)
  [18] org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.send (ResponseBodyEmitter.java:183)
  [19] org.springframework.web.servlet.mvc.method.annotation.SseEmitter.send (SseEmitter.java:126)
  [20] org.springframework.web.servlet.mvc.method.annotation.ReactiveTypeHandler$SseEmitterSubscriber.send (ReactiveTypeHandler.java:365)
  [21] org.springframework.web.servlet.mvc.method.annotation.ReactiveTypeHandler$AbstractEmitterSubscriber.run (ReactiveTypeHandler.java:308)
  [22] java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1,128)
  [23] java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
  [24] java.lang.Thread.run (Thread.java:834)
```

~Looking at the code, the [`ResponseBodyEmitter`](https://github.com/spring-projects/spring-framework/blob/v5.2.5.RELEASE/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/ResponseBodyEmitter.java) created by the [`ResponseBodyEmitterReturnValueHandler`](https://github.com/spring-projects/spring-framework/blob/v5.2.5.RELEASE/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/ResponseBodyEmitterReturnValueHandler.java)/[`ReactiveTypeHandler`](https://github.com/spring-projects/spring-framework/blob/v5.2.5.RELEASE/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/ReactiveTypeHandler.java) should not be writing any HTTP response headers outside of the [`extendResponse`](https://github.com/spring-projects/spring-framework/blob/v5.2.5.RELEASE/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/ResponseBodyEmitterReturnValueHandler.java#L170) called in the servlet thread, but the `ReactiveTypeHandler` subscription's [`SseEmitter.send`](https://github.com/spring-projects/spring-framework/blob/v5.2.5.RELEASE/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/ReactiveTypeHandler.java#L308) call in the `TaskExecutor` thread is also invoking [`ServletServerHttpResponse.writeHeaders`](https://github.com/spring-projects/spring-framework/blob/v5.2.5.RELEASE/spring-web/src/main/java/org/springframework/http/server/ServletServerHttpResponse.java#L104) via the [`HttpMessageConvertingHandler.sendInternal`](https://github.com/spring-projects/spring-framework/blob/v5.2.5.RELEASE/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/ResponseBodyEmitterReturnValueHandler.java#L210-L211).~ EDIT: see comment below on spring-security HeaderWriterFilter behavior instead

Complete error log and `jdb` traces atttached:

* [20200508-jetty-httpfields-npe-busyloop.txt](https://github.com/spring-projects/spring-framework/files/4615930/20200508-jetty-httpfields-npe-busyloop.txt)
* [20200512-spring-reactive-unsafe-headers.txt](https://github.com/spring-projects/spring-framework/files/4615933/20200512-spring-reactive-unsafe-headers.txt)

EDIT: edited stack traces to censor custom package names; use the first `task-9` thread stack from the jdb traces as the example

**Comment by Chr3is** [comment]
Any new information about this issue? We're affected by this as well and we can't use the mentioned fix by @rwinch because we use cache-control.

**Comment by SpComb** [comment]
The problematic spring backend in our case did not need to override any Cache-Control headers, so we were able to deploy the `headerWriterFilter.setShouldWriteHeadersEagerly(true)` workaround. We can confirm that we are no longer seeing these NPEs as a result.

**Comment by rstoyanchev** [comment]
#11452 was closed as a duplicate. Not to get lost, it has a convenient test to reproduce the issue.

**Comment by waschmittel** [comment]
We also encountered this sporadically when utilizing `ResponseEntity<StreamingResponseBody>`. Can confirm that `headerWriterFilter.setShouldWriteHeadersEagerly(true)` fixes it for us, too.

**Comment by AhrazA** [comment]
We have encountered this, however `headerWriterFilter.setShouldWriteHeadersEagerly(true)` does not appear to solve the problem on our end.

**Comment by ogaltsov** [comment]
Also faced with the same problem, when using `ResponseEntity<StreamingResponseBody>`

**Comment by 2is10** [comment]
My team has seen sporadic test failures for all async endpoints that use `StreamingResponseBody` or, more generally, any async endpoints that use the `WebAsyncManager.startCallableProcessing` code path. All of these failures are due to `ConcurrentModificationException` in Spring Security’s `HeaderWriterFilter.writeHeaders`.  Some occur in the original dispatch thread, while unwinding the filter chain; the rest occur in the async dispatch thread when our code begins writing to the response.

The crux of the problem seems to be that `OnCommittedResponseWrapper` is used in multiple threads, but isn’t thread-safe. One simple solution would be to make it thread-safe. Its `boolean disableOnCommitted` field that’s used here:
```java
    private void doOnResponseCommitted() {
        if (!this.disableOnCommitted) {
            onResponseCommitted();
            disableOnResponseCommitted();
        }
    }
```
…could be changed to `final AtomicBoolean` and used thus:
```java
    private void doOnResponseCommitted() {
        if (!this.disableOnCommitted.getAndSet(true)) {
            onResponseCommitted();
        }
    }
```
An even simpler solution would be for `HeaderWriterFilter` to stop trying to write to the response from two different threads. Application code normally commits any given HTTP response from exactly one thread. If `HeaderWriterFilter` just trusted `OnCommittedResponseWrapper` to do its thing, there would be no race condition. That would mean deleting the `finally` block below:
```java
    try {
        filterChain.doFilter(headerWriterRequest, headerWriterResponse);
    }
    finally {
        headerWriterResponse.writeHeaders();
    }
```
Any reason not to?

For the time being, the workaround I’ve adopted is adding a `response.flushBuffer();` call just before the `return` statement in each affected async endpoint. That call commits the response synchronously in the main dispatch thread before async processing begins—before the race condition can develop.

**Comment by WeihmannTNG** [comment]
We are also affected by this bug when returning ResponseEntity<StreamingResponseBody>.

**Comment by jwedel** [comment]
We are also affected via https://github.com/spring-projects/spring-framework/issues/31543. 

Is there any idea how to fix this? We are seeing flaky tests on CI. 

@sbrannen 
Is there anything you could think of that we can do in out spring integration tests to work-around that issue until this underlying issue resolved?

Help is appreciated!

**Comment by tomasged** [comment]
We're also affected. Just seen this case yesterday on our production logs. We're not using the HttpServletResponse in our endpoints but ResponseEntity<StreamingResponseBody>, so we cannot apply the flushBuffer workaround without some re-doing. We wanted to set the cache control for some of the endpoints but not all of them plus adding always some custom headers, so we're not sure. what to apply here in the mean time.

Like my previous post says, help here will be appreciated.

**Comment by oleg-astakhov** [comment]
Another one with the same issue here. Getting the exception sporadically from controllers which return `ResponseEntity<StreamingResponseBody>`. And yes I'm writing Cache-Control headers. (Exception example at the end of the post).

My setup is Spring Boot: 3.2.3 with embedded Tomcat.

I recently migrated from Spring Boot 2 + Jetty, and I have never seen this exception before migration. It only started with SB3 + Tomcat. But the exception source is clearly Tomcat in my case. I can see that this issue persists for a long time already, and even though it happens once in 2-3 days, it gets me alerted every time. 

Does anybody experience the same issue with Jetty (and SpringBoot 3) ?

Also, I don't know if this is connected, but I've recently noticed that images were loading slower. I checked CDN statuses and was surprised to see `BYPASS` statuses. My `ResponseEntity<StreamingResponseBody>` image controllers were setting `Cache-Control: public` headers, but for some reason, there was a 2nd pair of `Cache-Control` header with a `private` value. Of course, `private` is what was causing `BYPASS` and slow loading. When I debugged the app, my code was not setting `private` anywhere, it was added somewhere implicitly. So the way I fixed it, is by how I add this header. 

Previously I did it as follows: 
```
final HttpHeaders headers = new org.springframework.http.HttpHeaders();
headers.setCacheControl(<my public value>);
...
return new ResponseEntity<>(stream, headers, HttpStatus.OK);
```

But now directly on instance of `HttpServletResponse`: 
```
response.setHeader("Cache-Control", "<my public value>");
```
and the problem with CDN is solved.
I still use `HttpHeaders ` instance for other headers, but `Cache-Control` I set explicitly on the `HttpServletResponse` instance.

So, I wonder, what happens if I set all headers directly on the `HttpServletResponse` and not via `org.springframework.http.HttpHeaders`...

Here's the relevant part of the stacktrace:

```
java.lang.NullPointerException: Cannot invoke "org.apache.tomcat.util.http.MimeHeaderField.getName()" because "this.headers[i]" is null
	at org.apache.tomcat.util.http.MimeHeaders.getValue(MimeHeaders.java:322)
	at org.apache.tomcat.util.http.MimeHeaders.getHeader(MimeHeaders.java:354)
	at org.apache.coyote.Response.containsHeader(Response.java:365)
	at org.apache.catalina.connector.Response.containsHeader(Response.java:1082)
	at org.apache.catalina.connector.ResponseFacade.containsHeader(ResponseFacade.java:309)
	at jakarta.servlet.http.HttpServletResponseWrapper.containsHeader(HttpServletResponseWrapper.java:65)
	at jakarta.servlet.http.HttpServletResponseWrapper.containsHeader(HttpServletResponseWrapper.java:65)
	at org.springframework.security.web.header.writers.HstsHeaderWriter.writeHeaders(HstsHeaderWriter.java:156)
	at org.springframework.security.web.header.HeaderWriterFilter.writeHeaders(HeaderWriterFilter.java:99)
	at org.springframework.security.web.header.HeaderWriterFilter$HeaderWriterResponse.writeHeaders(HeaderWriterFilter.java:132)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:93)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
```

**Comment by joakime** [comment]
Should probably change the title of this issue as it is not unique to Jetty or Jetty's `HttpFields` object anymore.

**Comment by jtaub** [comment]
A comment above says it only happened to them after upgrading to Spring Boot 3, but we've been experiencing the same issue in Spring Boot 2.7.18 (and many earlier versions)

- Only happens with `StreamingResponseBody`
- `shouldWriteHeadersEagerly = true` seems to reduce the probability of the error occurring, but doesn't eliminate it
- We're using Apache Tomcat/Catalina, not jetty. Results in a lot of misleading `ClientAbortException`s

**Comment by slissner** [comment]
Note that a similiar problem has been reported here: https://github.com/spring-projects/spring-security/issues/7224#issue-477366635

The author to that ticket notes:

> The Exception can be prevented by @DirtiesContext, but this slows down the test alot and can not be used when calling mockMvc.perform multiple times in a single test-method.

I am going to use `@DirtiesContext` as well for a work around. At least it should make the CI pass.

**Comment by slissner** [comment]
> We are also affected via [spring-projects/spring-framework#31543](https://github.com/spring-projects/spring-framework/issues/31543).
> 
> Is there any idea how to fix this? We are seeing flaky tests on CI.
> 
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/104798?s=64&amp;u=e316a3b9d5ae74c3b31ace1a8361c90e84481daf&amp;v=4">@sbrannen](https://github.com/sbrannen) Is there anything you could think of that we can do in out spring integration tests to work-around that issue until this underlying issue resolved?
> 
> Help is appreciated!

@tomasged Other participants to this thread have also talked about problems with MockMvc. Albeit you have a point with your comment in the strict sense, broader research on the problem of `ConcurrentModificationException` and `StreamingResponseBody` have let me to this thread. I shared my comment to help others with similar problems. If this is of inconvenience for you, I apologize.

**Comment by tomasged** [comment]
No need to apologize. Mistakes can happen.

The thing is that fixing what's happening in production most likely will solve the issues with the tests, but we have separated github issues for the same cause, so it would be nicer to keep things separated to focus on the real issue. If not, the conversation will deviate to not fix the core issue since this issue is happening since 5 years ago. The tests are the less important thing  :( Real users are being affected.

(I would appreciated though that you quoted the person that asked for the integration tests in your original post like you did now to make sure that you were addressing the concerns of that person originally)

**Comment by netomi** [comment]
This is like a really annoying bug as it leads to random  `ConcurrentModificationExceptiion`s during test execution for endpoints returning `StreamingResponseBody`.
