### ISSUE TITLE
Current build failure due to com.nimbusds:oauth2-oidc-sdk:8.28.1

### ISSUE THREAD

**Issue by fhanik** [spring-projects/spring-security#9275]
Current build generates an error as it seems that the latest (8.28.1) `oauth2-oidc-sdk` artifact may be corrupt

> management "com.nimbusds:oauth2-oidc-sdk:8.27"

Temporarily resolves the issue

**Detailed Stack Trace**

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spring-security-oauth2-core:compileJava'.
> Could not resolve all files for configuration ':spring-security-oauth2-core:optional'.
   > Could not resolve com.nimbusds:oauth2-oidc-sdk:latest.release.
     Required by:
         project :spring-security-oauth2-core
      > Failed to list versions for com.nimbusds:oauth2-oidc-sdk.
         > Unable to load Maven meta-data from https://repo.spring.io/libs-snapshot/com/nimbusds/oauth2-oidc-sdk/maven-metadata.xml.
            > Could not HEAD 'https://repo.spring.io/libs-snapshot/com/nimbusds/oauth2-oidc-sdk/maven-metadata.xml'. Received status code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 7s
105 actionable tasks: 105 executed

A build scan cannot be produced as an error occurred gathering build data.
Please report this problem via https://ge.spring.io/help and include the following via copy/paste:

----------
Gradle version: 6.7.1
Plugin version: 3.2

org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':spring-security-oauth2-core:optional'.
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:104)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.access$000(ErrorHandlingConfigurationResolver.java:48)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getRoot(ErrorHandlingConfigurationResolver.java:203)
        at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationResult.getRootComponent(ResolveConfigurationResolutionBuildOperationResult.java:59)
        at com.gradle.scan.plugin.internal.b.e.a.h$a.b(SourceFile:116)
        at com.gradle.scan.plugin.internal.b.e.a.h$a.a(SourceFile:70)
        at com.gradle.scan.plugin.internal.b.e.a.h.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.b.e.a.g.a(SourceFile:149)
        at com.gradle.scan.plugin.internal.b.e.c.a(SourceFile:142)
        at com.gradle.scan.plugin.internal.k.a.f.a(SourceFile:12)
        at com.gradle.scan.plugin.internal.k.a$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.k.a.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.k.j.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.k.d.a(SourceFile:103)
        at com.gradle.scan.plugin.internal.k.f.a(SourceFile:48)
        at com.gradle.scan.plugin.internal.p.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.p.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.p.a.c(SourceFile:67)
Caused by: java.lang.RuntimeException: Problems reading data from Binary store in /tmp/gradle5125261502026218121.bin offset 88840 exists? true
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:132)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.lambda$create$0(StreamingResolutionResultBuilder.java:188)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory$SimpleStore.load(CachedStoreFactory.java:101)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:186)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:158)
        at org.gradle.api.internal.artifacts.result.DefaultResolutionResult.getRoot(DefaultResolutionResult.java:48)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getRoot(ErrorHandlingConfigurationResolver.java:201)
        at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationResult.getRootComponent(ResolveConfigurationResolutionBuildOperationResult.java:59)
        at com.gradle.scan.plugin.internal.b.e.a.h$a.b(SourceFile:116)
        at com.gradle.scan.plugin.internal.b.e.a.h$a.a(SourceFile:70)
        at com.gradle.scan.plugin.internal.b.e.a.h.a(SourceFile:51)
        at com.gradle.scan.plugin.internal.b.e.a.g.a(SourceFile:149)
        at com.gradle.scan.plugin.internal.b.e.c.a(SourceFile:142)
        at com.gradle.scan.plugin.internal.k.a.f.a(SourceFile:12)
        at com.gradle.scan.plugin.internal.k.a$c.finished(SourceFile:154)
        at com.gradle.scan.plugin.internal.k.a.a(SourceFile:65)
        at com.gradle.scan.plugin.internal.k.j.a(SourceFile:58)
        at com.gradle.scan.plugin.internal.k.d.a(SourceFile:103)
        at com.gradle.scan.plugin.internal.k.f.a(SourceFile:48)
        at com.gradle.scan.plugin.internal.p.a$a.a(SourceFile:31)
        at com.gradle.scan.plugin.internal.p.a$a.a(SourceFile:20)
        at com.gradle.scan.plugin.internal.p.a.c(SourceFile:67)
Caused by: java.lang.IllegalStateException: Corrupt serialized resolution result. Cannot find selected module (22) for optional -> com.nimbusds:oauth2-oidc-sdk
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.DefaultResolutionResultBuilder.visitOutgoingEdges(DefaultResolutionResultBuilder.java:83)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.deserialize(StreamingResolutionResultBuilder.java:238)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:130)
        ... 21 more

----------
```

**Comment by jzheaux** [comment]
I think this is related to https://github.com/spring-gradle-plugins/spring-build-conventions/issues/90

**Comment by jzheaux** [comment]
I don't think this is a problem with a single dependency. Spring recently changed [the way authentication works](https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020) with its repositories.

I've [filed a ticket](https://github.com/spring-gradle-plugins/spring-build-conventions/issues/90) in Spring Build Conventions to look into the issue further.
